'use client';

import { useMemo, useState } from 'react';
import './poolcost.css';

const OFFER_URL = 'https://eu.beatbot.com/el/products/sora-70'; // Replace with approved affiliate tracking URL before paid traffic.
const useCases={home:['Κύρια κατοικία','Λιγότερη ρουτίνα. Περισσότερος χρόνος μέσα στην πισίνα.'],exochiko:['Εξοχικό','Το Σαββατοκύριακο δεν πρέπει να ξεκινά με απόχη και βούρτσα.'],villa:['Villa / Airbnb','Η πισίνα πρέπει να είναι έτοιμη πριν από κάθε άφιξη επισκέπτη.'],hotel:['Hospitality','Μετέφερε εργατοώρες από επαναλαμβανόμενο καθαρισμό σε δουλειές που βλέπει ο επισκέπτης.']};
export default function PoolCostAI(){const[kind,setKind]=useState('exochiko');const[cleans,setCleans]=useState(2);const[minutes,setMinutes]=useState(45);const[weeks,setWeeks]=useState(24);const[cost,setCost]=useState(25);const result=useMemo(()=>({hours:Math.round(cleans*minutes/60*weeks),annual:Math.round(cleans*cost*weeks),sessions:cleans*weeks}),[cleans,minutes,weeks,cost]);const[title,story]=useCases[kind];return <main className="pool-page">
<nav><a className="brand" href="#top">POOLCOST <i>AI</i></a><a href="#calc">Calculator</a><a href="#compare">Σύγκριση</a><a className="navCta" href={OFFER_URL} target="_blank" rel="sponsored nofollow noopener">Δες την προσφορά ↗</a></nav>
<section id="top" className="hero"><div className="eyebrow">AEGEAN AUTONOMY · POOL INTELLIGENCE</div><h1>Πόσο σου κοστίζει<br/><em>πραγματικά</em> η πισίνα σου;</h1><p className="lead">Μέτρα πρώτα τον χρόνο και το κόστος του καθαρισμού σου. Μετά δες αν ένα all‑in‑one pool robot έχει νόημα για σένα.</p><div className="heroActions"><a className="primary" href="#calc">Υπολόγισέ το σε 30″ ↓</a><a className="ghost" href="#solution">Δες τη λύση</a></div><div className="waterCard"><span>01</span><strong>Δεν ξεκινάμε από το προϊόν.</strong><p>Ξεκινάμε από τη δική σου πισίνα, τη χρήση και το πραγματικό σου κόστος.</p></div></section>
<section id="calc" className="calcWrap"><div className="sectionHead"><small>POOL COST CALCULATOR</small><h2>Βάλε τα δικά σου δεδομένα.</h2><p>Δεν χρησιμοποιούμε «μέσες» υποθετικές χρεώσεις. Το αποτέλεσμα βασίζεται στις τιμές που δίνεις εσύ.</p></div><div className="calcGrid"><div className="controls"><label>Χρήση πισίνας<select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(useCases).map(([k,v])=><option key={k} value={k}>{v[0]}</option>)}</select></label><label>Καθαρισμοί / εβδομάδα <b>{cleans}</b><input type="range" min="1" max="7" value={cleans} onChange={e=>setCleans(+e.target.value)}/></label><label>Λεπτά / καθαρισμό <b>{minutes}</b><input type="range" min="15" max="180" step="15" value={minutes} onChange={e=>setMinutes(+e.target.value)}/></label><label>Εβδομάδες λειτουργίας / έτος <b>{weeks}</b><input type="range" min="4" max="52" step="2" value={weeks} onChange={e=>setWeeks(+e.target.value)}/></label><label>Κόστος ανά καθαρισμό (€)<input className="number" type="number" min="0" value={cost} onChange={e=>setCost(+e.target.value||0)}/></label></div><div className="result"><small>Η ΔΙΚΗ ΣΟΥ ΕΚΤΙΜΗΣΗ</small><div><strong>{result.sessions}</strong><span>καθαρισμοί / έτος</span></div><div><strong>{result.hours}h</strong><span>χρόνος / έτος</span></div><div><strong>€{result.annual.toLocaleString('el-GR')}</strong><span>κόστος / έτος*</span></div><p>*Με βάση αποκλειστικά τα στοιχεία που εισήγαγες. Δεν αποτελεί υπόσχεση εξοικονόμησης.</p></div></div></section>
<section className="persona"><small>YOUR USE CASE</small><h2>{title}</h2><p>{story}</p></section>
<section id="solution" className="solution"><div className="solutionCopy"><small>02 · PRODUCT REVEAL</small><h2>Ένα robot.<br/>Πέντε ζώνες καθαρισμού.</h2><p>Το <b>Beatbot Sora 70</b> είναι cordless robot για πισίνες έως 300 m². Η Beatbot δηλώνει καθαρισμό επιφάνειας, πυθμένα, τοίχων, waterline και ρηχών πλατφορμών.</p><div className="zones">{['Επιφάνεια','Πυθμένας','Τοίχοι','Waterline','Πλατφόρμες'].map((z,i)=><div key={z}><span>0{i+1}</span>{z}</div>)}</div></div><div className="specOrb"><div>25,700<small>LPH suction</small></div><div>6L<small>filter basket</small></div><div>5–7h<small>runtime by mode</small></div><div>300m²<small>coverage / charge</small></div></div></section>
<section id="compare" className="compare"><div className="sectionHead"><small>HONEST VALUE CHECK</small><h2>Σύγκρινε λύσεις, όχι slogans.</h2><p>Οι τιμές αλλάζουν. Γι’ αυτό το τελικό CTA οδηγεί στην τρέχουσα επίσημη ευρωπαϊκή προσφορά.</p></div><div className="priceStage"><div><small>BEATBOT EU · SORA 70</small><strong>€1.109</strong><span>τιμή που επαληθεύτηκε 04/09/2026</span></div><div className="vs">VS</div><div><small>PREMIUM ALL‑IN‑ONE CLASS IN GR</small><strong>€1.799*</strong><span>*ενδεικτικός comparator — re-check πριν από καμπάνια</span></div></div><p className="honesty">Δεν ισχυριζόμαστε ότι τα προϊόντα είναι τεχνικά πανομοιότυπα. Η σύγκριση αφορά premium cordless all‑in‑one κατηγορία αντίστοιχης χρήσης. Κάθε paid campaign πρέπει να επανελέγχει τιμή, διαθεσιμότητα και όρους.</p></section>
<section className="trust"><div><small>3 YEARS</small><h3>Warranty</h3><p>Η Beatbot EU αναφέρει 3ετή κάλυψη για το Sora 70.</p></div><div><small>NO PRO INSTALL</small><h3>Charge. Set. Clean.</h3><p>Δεν απαιτεί μόνιμη υδραυλική ή ηλεκτρολογική εγκατάσταση.</p></div><div><small>EU SUPPORT</small><h3>European channel</h3><p>Επίσημο ευρωπαϊκό storefront και support.</p></div></section>
<section className="final"><small>POOLCOST AI VERDICT</small><h2>Αν ο χρόνος σου αξίζει περισσότερο από τη ρουτίνα της πισίνας, αξίζει να το εξετάσεις.</h2><p>Έλεγξε την τρέχουσα τιμή, συμβατότητα και όρους απευθείας στην επίσημη ευρωπαϊκή σελίδα.</p><a className="primary big" href={OFFER_URL} target="_blank" rel="sponsored nofollow noopener">Έλεγξε την τρέχουσα προσφορά ↗</a><p className="disclosure">Prototype affiliate funnel: το CTA είναι προσωρινά το επίσημο product URL. Πριν από paid traffic αντικαθίσταται από το εγκεκριμένο affiliate tracking URL.</p></section><footer>POOLCOST AI · Independent decision experience · 2026</footer></main>}
