'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
import OpportunityQuadrant from '@/components/analytics/OpportunityQuadrant';
import styles from './forecast-products.module.css';

const num=(v,d=1)=>v===null||v===undefined||Number.isNaN(Number(v))?'—':Number(v).toLocaleString('el-GR',{maximumFractionDigits:d});
const money=(v,d=2)=>v===null||v===undefined||Number.isNaN(Number(v))?'—':`€${Number(v).toLocaleString('el-GR',{minimumFractionDigits:d,maximumFractionDigits:d})}`;
const pct=(v,d=2)=>v===null||v===undefined?'—':`${num(v,d)}%`;
const list=v=>Array.isArray(v)?v:[];

export default function ForecastProducts(){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[query,setQuery]=useState('');
 async function load(){setLoading(true);setError('');const {data,error}=await supabase.rpc('admin_top_forecasted_products',{p_limit:200});if(error)setError(error.message);else setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?rows.filter(x=>`${x.canonical_title||''} ${x.merchant_name||''} ${x.category||''} ${x.subcategory||''} ${list(x.semantic_keywords).join(' ')}`.toLowerCase().includes(q)):rows},[rows,query]);
 async function generateProfile(row){setBusy(row.product_id);setError('');try{const {data:{session}}=await supabase.auth.getSession();const r=await fetch('https://rpfadpdnnxequgvdcfoq.supabase.co/functions/v1/admin-intelligence-gateway',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${session?.access_token||''}`},body:JSON.stringify({action:'product_profile',product:row})});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||`HTTP ${r.status}`);await load()}catch(e){setError(String(e.message||e))}finally{setBusy('')}}
 if(loading)return <main className={styles.wrap}><div className={styles.loading}>Loading validated affiliate product forecasts…</div></main>;
 const profiled=rows.filter(x=>x.promotion_description).length;
 return <main className={styles.wrap}>
  <header className={styles.hero}><div><span className={styles.eyebrow}>Affiliate Opportunity Engine</span><h1>Top Forecasted Products</h1><p>One decision table combining semantic fit, market demand, competition, merchant program conversion economics, profitability and promotion intelligence.</p></div><button onClick={load}>↻ Refresh</button></header>
  {error&&<div className={styles.error}>{error}</div>}
  <section className={styles.truth}><div><b>{rows.length}</b><span>validated forecastable products</span></div><div><b>{profiled}</b><span>AI marketing profiles</span></div><div><b>{rows.filter(x=>x.network_conversion_rate!==null).length}</b><span>with network CVR</span></div><div><b>{rows.filter(x=>x.modeled_break_even_cpc_eur!==null).length}</b><span>with break-even CPC model</span></div><p>{rows.length?'Observed merchant-program KPIs + evidence-grounded product scenarios':'No rows are fabricated. Product ranking stays empty until clean validated pains produce validated products.'}</p></section>

  <section className={styles.grid2}><div className={styles.panel}><span className={styles.eyebrow}>Infographic</span><h2>Demand × Competition × Pain</h2><OpportunityQuadrant items={rows}/><p className={styles.note}>X = observed evidence-derived competition score, Y = demand score, bubble size = pain-fit score. This is not market share.</p></div><div className={styles.panel}><span className={styles.eyebrow}>Affiliate economics</span><h2>How rank is built</h2><div className={styles.formula}><div><b>25%</b><span>Final product opportunity</span></div><div><b>15%</b><span>Pain-gap fit</span></div><div><b>10%</b><span>Greek demand</span></div><div><b>10%</b><span>Inverse competition</span></div><div><b>10%</b><span>Evidence confidence</span></div><div><b>10%</b><span>CVR percentile</span></div><div><b>8%</b><span>EPC percentile</span></div><div><b>7%</b><span>Approval percentile</span></div><div><b>5%</b><span>Program commercial score</span></div></div><p className={styles.note}>Conversion economics are merchant-program baselines. They become first-party performance only after SocialMarket records its own clicks/conversions.</p></div></section>

  <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>Final decision table</span><h2>Forecasted affiliate products</h2></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product, merchant, keyword…"/></div>
   {filtered.length?<div className={styles.tableWrap}><table><thead><tr><th>#</th><th>Product / Merchant</th><th>Semantic taxonomy</th><th>Forecast</th><th>Pain / Demand / Competition</th><th>Affiliate KPIs</th><th>Economics</th><th>Semantic keywords</th><th>Low-competition tags</th><th>Unique promotion</th><th>Tracking</th><th>Profile</th></tr></thead><tbody>{filtered.map((x,i)=><tr key={`${x.product_id}-${x.offer_id}`}><td><b>{i+1}</b></td><td className={styles.main}><b>{x.canonical_title}</b><small>{x.merchant_name}{x.brand_name?` · ${x.brand_name}`:''}</small></td><td><b>{x.category||'—'}</b><small>{x.subcategory||'Category-level only'}</small></td><td><strong>{num(x.affiliate_forecast_score,1)}</strong><small>product opp. {num(x.final_opportunity_score,1)} · evidence {pct(x.product_evidence_confidence,0)}</small></td><td><span>P {num(x.pain_gap_fit_score,0)}</span><span>D {num(x.greek_demand_score,0)}</span><span>C {num(x.competition_score,0)}</span></td><td><span>CVR {pct(x.network_conversion_rate)}</span><span>EPC {num(x.network_epc,2)}</span><span>Approval {pct(x.network_approval_rate)}</span><small>validation {num(x.network_validation_days,1)}d</small></td><td><b>{money(x.expected_commission_eur)}</b><small>commission / conversion</small><span>{money(x.modeled_commission_per_100_clicks)} /100 modeled</span><span>break-even CPC {money(x.modeled_break_even_cpc_eur,4)}</span></td><td><div className={styles.tags}>{list(x.semantic_keywords).map(k=><span key={k}>{k}</span>)}</div>{!list(x.semantic_keywords).length&&<small>Profile not generated</small>}</td><td><div className={styles.tags}>{list(x.low_competition_tags).map(k=><span key={k}>{k}</span>)}</div>{!list(x.low_competition_tags).length&&<small>Not measured/generated</small>}</td><td className={styles.copy}>{x.promotion_description||<small>Generate evidence-grounded profile.</small>}</td><td><a href={x.tracking_url} target="_blank" rel="noreferrer">Affiliate URL ↗</a><small>{x.tracking_url}</small></td><td>{x.promotion_description?<><span className={styles.ok}>{x.profile_audit_status||'profiled'}</span><small>{num(x.forecast_confidence,0)}% forecast confidence</small></>:<button onClick={()=>generateProfile(x)} disabled={busy===x.product_id}>{busy===x.product_id?'Generating…':'✦ Generate AI Profile'}</button>}</td></tr>)}</tbody></table></div>:<div className={styles.empty}><h3>No validated forecastable products yet</h3><p>The previous pain clusters were semantically contaminated and have been removed from trusted use. The Product Intelligence pipeline will only populate this table after clean semantic pains and canonical product taxonomy pass audit.</p></div>}
  </section>
 </main>
}
