'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
import styles from './forecast-products.module.css';

const num=(v,d=1)=>v===null||v===undefined||Number.isNaN(Number(v))?'—':Number(v).toLocaleString('el-GR',{maximumFractionDigits:d});
const money=v=>v===null||v===undefined?'—':`€${Number(v).toLocaleString('el-GR',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const arr=v=>Array.isArray(v)?v:[];
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
const help={rank:'Final promotion rank: deterministic market, conversion/commercial and product signals + AI product/creative fit, reduced by independent Skeptic risk.',network:'Observed Linkwise/program baseline. It is not observed sales for this exact product.',forecast:'Deterministic product economics: network conversion × approval × expected product commission. It is a forecast baseline, not observed product revenue.',firstParty:'Observed SocialMarket traffic/conversions from the last 30 days. If empty, no first-party claim is made.',risk:'Independent ranking skeptic risk: higher means greater promotion uncertainty.'};

export default function ForecastProducts(){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[band,setBand]=useState('');
 async function load(){setLoading(true);setError('');const {data,error}=await supabase.rpc('admin_top_ranked_products',{p_limit:500,p_band:band||null});if(error)setError(error.message);else setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[band]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?rows.filter(x=>{const seo=obj(x.seo_content);return `${x.product_name||''} ${x.merchant_name||''} ${x.brand_name||''} ${x.category||''} ${x.promotion_angle||''} ${seo.title||''} ${arr(seo.keywords).join(' ')}`.toLowerCase().includes(q)}):rows},[rows,query]);
 if(loading)return <main className={styles.wrap}><div className={styles.loading}>Loading product ranking…</div></main>;
 return <main className={styles.wrap}>
  <header className={styles.hero}><div><span className={styles.eyebrow}>Ranking V3.3 · Conversion + SEO Decision Engine</span><h1>Products to Promote</h1><p>Top-ranked affiliate products with deterministic economics, AI strategy + skeptic review, full feed characteristics, tracking URL and evidence-constrained SEO copy.</p></div><div className={styles.heroActions}><a href="/analytics">← Dashboard</a><button onClick={load}>↻ Refresh</button></div></header>
  {error&&<div className={styles.error}>{error}</div>}
  <section className={styles.controls}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product, merchant, category or SEO keyword…"/><select value={band} onChange={e=>setBand(e.target.value)}><option value="">All ranked</option><option value="PROMOTE_NOW">Promote now</option><option value="HIGH_POTENTIAL">High potential</option><option value="TEST">Test</option><option value="WATCHLIST">Watchlist</option></select><span>{filtered.length} products</span></section>
  {filtered.length?<section className={styles.list}>{filtered.map(x=>{const k=obj(x.kpi_snapshot),net=obj(k.network_baseline),model=obj(k.modeled_product_economics),fp=obj(k.first_party_30d),attrs=obj(x.product_attributes),seo=obj(x.seo_content),extras=obj(attrs.extra_attributes);return <article className={styles.row} key={`${x.run_id}-${x.source_record_hash}`}>
   <div className={styles.pos}>#{x.global_rank}</div>
   <div className={styles.identity}><b>{x.product_name}</b><span>{x.merchant_name}{x.brand_name?` · ${x.brand_name}`:''}</span><small>{x.category||'—'}{x.subcategory?` › ${x.subcategory}`:''}</small><p>{seo.short_description||x.promotion_angle||x.promotion_reason||'—'}</p><div className={styles.tags}>{arr(x.recommended_channels).map(c=><span key={c}>{c}</span>)}{arr(x.risk_flags).slice(0,2).map(r=><i key={r}>{r}</i>)}</div></div>
   <div className={styles.score}><strong title={help.rank}>{num(x.rank_score,1)}</strong><em>{x.rank_band?.replaceAll('_',' ')}</em><span>AI confidence <b>{num(x.ai_confidence,0)}%</b></span></div>
   <div className={styles.metrics}><span title={help.network}>Network CVR <b>{net.conversion_rate_pct===undefined?'—':`${num(net.conversion_rate_pct,2)}%`}</b></span><span title={help.network}>Network EPC <b>{money(net.epc_eur)}</b></span><span title={help.forecast}>Approved €/100 clicks <b>{money(model.expected_approved_commission_per_100_clicks_eur)}</b></span><span title={help.forecast}>Break-even CPC <b>{money(model.break_even_cpc_eur)}</b></span><span>Commission / sale <b>{money(x.expected_commission_eur)}</b></span><span>Price <b>{money(x.effective_price)}</b></span><span>Network score <b>{num(x.network_performance_score,0)}</b></span><span title={help.risk}>Risk <b>{num(x.ai_risk_score,0)}</b></span></div>
   <div className={styles.action}>{x.tracking_url?<a href={x.tracking_url} target="_blank" rel="noreferrer">Promote link ↗</a>:<span>No link</span>}<small>{x.promotion_reason||x.ai_summary||''}</small>{fp.status==='observed'&&<small title={help.firstParty}>Observed 30d: {num(fp.outbound_clicks,0)} clicks · {num(fp.approved_conversions,0)} approved · {money(fp.approved_commission_eur)}</small>}</div>
   <details className={styles.details}><summary>SEO & product details</summary><div className={styles.detailGrid}>
    <section><h4>AI SEO</h4><dl><dt>SEO title</dt><dd>{seo.title||'—'}</dd><dt>Meta description</dt><dd>{seo.meta_description||'—'}</dd><dt>Search intent</dt><dd>{seo.search_intent||'—'}</dd><dt>Slug</dt><dd>{seo.slug||'—'}</dd></dl>{arr(seo.keywords).length>0&&<div className={styles.keywordList}>{arr(seo.keywords).map(k=><span key={k}>{k}</span>)}</div>}<p className={styles.seoDescription}>{seo.description||'SEO content will be generated by the ranking pipeline.'}</p>{arr(seo.feature_bullets).length>0&&<ul>{arr(seo.feature_bullets).map(b=><li key={b}>{b}</li>)}</ul>}</section>
    <section><h4>Feed characteristics</h4><dl><dt>Brand / model</dt><dd>{[x.brand_name,x.model_name].filter(Boolean).join(' · ')||'—'}</dd><dt>Colour</dt><dd>{attrs.colour||'—'}</dd><dt>Size</dt><dd>{attrs.size||'—'}</dd><dt>Availability</dt><dd>{attrs.availability||String(x.in_stock??'—')}</dd><dt>GTIN</dt><dd>{attrs.gtin||'—'}</dd><dt>MPN / SKU</dt><dd>{attrs.mpn||'—'}</dd><dt>Valid until</dt><dd>{attrs.valid_to||'—'}</dd><dt>Images</dt><dd>{1+arr(attrs.extra_images).length}</dd></dl>{Object.keys(extras).length>0&&<div className={styles.extraAttrs}>{Object.entries(extras).slice(0,12).map(([k,v])=><span key={k}><b>{k}</b> {typeof v==='object'?JSON.stringify(v):String(v)}</span>)}</div>}</section>
    <section className={styles.wide}><h4>Original source description</h4><p>{attrs.original_description||'—'}</p><div className={styles.links}>{x.tracking_url&&<a href={x.tracking_url} target="_blank" rel="noreferrer">Affiliate tracking URL ↗</a>}{attrs.target_url&&<a href={attrs.target_url} target="_blank" rel="noreferrer">Merchant destination ↗</a>}</div></section>
   </div></details>
  </article>})}</section>:<section className={styles.empty}><h3>No ranking results yet</h3><p>The current full production ranking is still completing. The next V3.3 run will persist conversion KPIs, full product facts and SEO content.</p></section>}
 </main>
}
