import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createRemoteJWKSet, jwtVerify } from 'npm:jose@6.1.0'
import postgres from 'https://deno.land/x/postgresjs@v3.4.5/mod.js'

const sql=postgres(Deno.env.get('SUPABASE_DB_URL')!,{prepare:false})
const ISSUER='https://token.actions.githubusercontent.com'
const AUDIENCE='socialmarket-supabase-worker'
const REPOSITORY_ID='1329707883'
const REPOSITORY='vmoulakakis/Socialmarket'
const ALLOWED=new Set(['vmoulakakis/Socialmarket/.github/workflows/generic-evidence-intelligence.yml@refs/heads/main'])
const JWKS=createRemoteJWKSet(new URL(`${ISSUER}/.well-known/jwks`))
const clamp=(n:number,a=0,b=100)=>Math.max(a,Math.min(b,n))
function json(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json'}})}
function domain(u:string|null){try{return new URL(u||'').hostname.toLowerCase().replace(/^www\./,'')}catch{return ''}}
async function auth(req:Request){const h=req.headers.get('authorization')||'';if(!h.startsWith('Bearer '))throw new Error('missing_oidc');const {payload}=await jwtVerify(h.slice(7),JWKS,{issuer:ISSUER,audience:AUDIENCE});if(String(payload.repository_id||'')!==REPOSITORY_ID||String(payload.repository||'')!==REPOSITORY||String(payload.ref||'')!=='refs/heads/main'||!ALLOWED.has(String(payload.workflow_ref||'')))throw new Error('oidc_not_allowed');return payload}
async function claim(limit:number,worker:string,collectionType:string){return await sql`with picked as (select id from ops.collection_jobs where status='queued' and not_before<=now() and collection_type=${collectionType} order by priority desc,requested_at asc for update skip locked limit ${Math.max(1,Math.min(limit,60))}), upd as (update ops.collection_jobs j set status='running',lease_owner=${worker},lease_expires_at=now()+interval '90 minutes',attempt_count=attempt_count+1 from picked p where j.id=p.id returning j.*) select * from upd`}
async function save(result:any){const jobId=String(result.job_id||''),entityType=String(result.entity_type||''),entityId=String(result.entity_id||'');if(!jobId||!entityType||!entityId)throw new Error('missing_ids');let obs=0,clusters=0;
 for(const e of (Array.isArray(result.evidence)?result.evidence:[]).slice(0,200)){const kind=String(e.source_kind||'web_observation').slice(0,80),url=e.source_url||null,body=e.body||null,title=e.title||null,platform=e.platform||null,collector=String(e.collector||'generic_worker').slice(0,80),confidence=clamp(Number(e.confidence??0.55),0,1);const hash=String(e.content_hash||await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${kind}|${url||''}|${title||''}|${body||''}`)).then(b=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')));await sql`insert into evidence.observations(entity_type,entity_id,source_kind,platform,source_url,source_domain,collector,title,body,metrics,metadata,confidence,validation_status,content_hash) values(${entityType},${entityId},${kind},${platform},${url},${domain(url)||null},${collector},${title},${body},${sql.json(e.metrics||{})},${sql.json(e.metadata||{})},${confidence},${confidence>=0.7?'validated':'pending'},${hash}) on conflict(entity_type,entity_id,source_kind,content_hash) do update set collected_at=now(),confidence=greatest(evidence.observations.confidence,excluded.confidence),metadata=evidence.observations.metadata||excluded.metadata`;obs++}
 for(const c of (Array.isArray(result.clusters)?result.clusters:[]).slice(0,100)){const text=String(c.canonical_text||'').trim();if(text.length<12)continue;const verdict=String(c.validation_status||'pending');await sql`insert into evidence.semantic_clusters(entity_type,entity_id,cluster_type,canonical_text,category,subcategory,evidence_count,source_diversity,frequency_score,engagement_score,demand_score,competition_score,pain_severity,commercial_intent,audit_score,confidence,validation_status,embedding_status,metadata,updated_at) values(${entityType},${entityId},${String(c.cluster_type||'pain')},${text},${c.category||null},${c.subcategory||null},${Number(c.evidence_count||0)},${Number(c.source_diversity||0)},${c.frequency_score??null},${c.engagement_score??null},${c.demand_score??null},${c.competition_score??null},${c.pain_severity??null},${c.commercial_intent??null},${c.audit_score??null},${clamp(Number(c.confidence??0.5),0,1)},${verdict},${verdict==='validated'?'pending':'stale'},${sql.json(c.metadata||{})},now()) on conflict(entity_type,entity_id,cluster_type,md5(canonical_text)) do update set evidence_count=excluded.evidence_count,source_diversity=excluded.source_diversity,demand_score=excluded.demand_score,competition_score=excluded.competition_score,pain_severity=excluded.pain_severity,commercial_intent=excluded.commercial_intent,audit_score=excluded.audit_score,confidence=excluded.confidence,validation_status=excluded.validation_status,embedding_status=case when evidence.semantic_clusters.validation_status=excluded.validation_status and evidence.semantic_clusters.embedding_status='ready' then 'ready' else excluded.embedding_status end,metadata=evidence.semantic_clusters.metadata||excluded.metadata,updated_at=now()`;clusters++}
 await sql`update ops.collection_jobs set status='completed',completed_at=now(),lease_owner=null,lease_expires_at=null,last_error=null where id=${jobId} and entity_id=${entityId}`;return {observations:obs,clusters}}
Deno.serve(async(req)=>{if(req.method==='GET')return json({ok:true,service:'evidence-gateway',version:'1.0'});if(req.method!=='POST')return json({error:'method_not_allowed'},405);try{const claims=await auth(req);const b=await req.json();const action=String(b.action||'');if(action==='claim')return json({ok:true,jobs:await claim(Number(b.limit||40),String(b.worker||'generic-evidence-worker'),String(b.collection_type||'pain_discovery')),workflow_ref:claims.workflow_ref});if(action==='save')return json({ok:true,result:await save(b.result||{})});if(action==='fail'){await sql`update ops.collection_jobs set status=case when attempt_count>=4 then 'failed' else 'queued' end,last_error=${String(b.error||'worker_failed').slice(0,1200)},lease_owner=null,lease_expires_at=null,not_before=now()+interval '30 minutes' where id=${String(b.job_id||'')}`;return json({ok:true})}throw new Error('action_not_allowed')}catch(e){console.error(e);return json({error:String(e instanceof Error?e.message:e)},401)}})
