'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
import styles from './monitor.module.css';
const fmt=v=>v?new Date(v).toLocaleString('el-GR'):'—';
export default function Monitor(){
  const [jobs,setJobs]=useState([]),[incidents,setIncidents]=useState([]),[health,setHealth]=useState([]),[clicks,setClicks]=useState([]),[runs,setRuns]=useState([]),[err,setErr]=useState('');
  useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t)},[]);
  async function load(){const [j,i,h,c,r]=await Promise.all([supabase.from('social_publish_jobs').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('social_incidents').select('*').order('last_seen_at',{ascending:false}).limit(100),supabase.from('social_provider_health').select('*').order('provider'),supabase.from('affiliate_click_events').select('id,slug,platform,clicked_at').order('clicked_at',{ascending:false}).limit(200),supabase.from('product_to_post_runs').select('id,status,summary,error,created_at').order('created_at',{ascending:false}).limit(30)]);const e=[j,i,h,c,r].find(x=>x.error)?.error;setErr(e?.message||'');setJobs(j.data||[]);setIncidents(i.data||[]);setHealth(h.data||[]);setClicks(c.data||[]);setRuns(r.data||[])}
  const k=useMemo(()=>({scheduled:jobs.filter(x=>['scheduled','published'].includes(x.status)).length,failed:jobs.filter(x=>x.status==='failed').length,open:incidents.filter(x=>x.status==='open').length,clicks:clicks.length}),[jobs,incidents,clicks]);
  const bio=typeof window!=='undefined'?`${window.location.origin}/links/tiktok`:'/links/tiktok';
  return <main className={styles.page}><section className={styles.hero}><div><div className="eyebrow">AUTONOMOUS MARKETING OPS</div><h1>Monitoring & Problems</h1><p>Παρακολουθείς μόνο ό,τι έχει σημασία: publisher health, scheduled posts, failures, clicks και incidents.</p></div><button onClick={load}>↻ Refresh</button></section>{err?<div className={styles.alert}>Database/API: {err}</div>:null}<section className={styles.kpis}><article><small>Scheduled / published</small><b>{k.scheduled}</b></article><article><small>Publish failures</small><b>{k.failed}</b></article><article><small>Open incidents</small><b>{k.open}</b></article><article><small>Recent tracked clicks</small><b>{k.clicks}</b></article></section><section className={styles.card}><div className="eyebrow">TIKTOK LINK IN BIO</div><h2>{bio}</h2><p>Αυτό είναι το σταθερό URL του TikTok bio. Τα προϊόντα μέσα αλλάζουν αυτόματα.</p></section><section className={styles.grid}><article className={styles.card}><h2>Provider health</h2>{health.length?health.map(x=><div className={styles.row} key={`${x.provider}-${x.platform}`}><div><b>{x.provider} · {x.platform}</b><small>{fmt(x.checked_at)}</small></div><span className={x.healthy?styles.ok:styles.bad}>{x.healthy?'healthy':x.configured?'problem':'not configured'}</span></div>):<p>No provider checks yet.</p>}</article><article className={styles.card}><h2>Incidents</h2>{incidents.length?incidents.slice(0,25).map(x=><div className={styles.row} key={x.id}><div><b>{x.incident_type}</b><small>{x.platform||'engine'} · {x.message}</small></div><span className={x.status==='resolved'?styles.ok:styles.bad}>{x.status}</span></div>):<p>No incidents.</p>}</article></section><section className={styles.card}><h2>Publishing queue</h2><div className={styles.table}>{jobs.slice(0,40).map(x=><div className={styles.tr} key={x.id}><span>{x.platform}</span><span>{x.actual_provider||x.preferred_provider}</span><span>{x.status}</span><span>{x.attempt_count}</span><span>{fmt(x.created_at)}</span></div>)}</div></section><section className={styles.card}><h2>Recent engine runs</h2>{runs.map(x=><div className={styles.row} key={x.id}><div><b>{x.status}</b><small>{fmt(x.created_at)} · selected {x.summary?.selected??'—'} · successful {x.summary?.successful??'—'}</small></div>{x.error?<span className={styles.bad}>error</span>:<span className={styles.ok}>ok</span>}</div>)}</section></main>
}
