export const industries={
'production-processing':{name:'Production & Processing',title:'Εξοπλισμός παραγωγής & αυτοματοποίησης για ελληνικές επιχειρήσεις',intro:'Λύσεις για mixing, filling, capping και μικρή/μεσαία παραγωγή. Η επιλογή γίνεται με βάση throughput, τεχνικό fit, landed cost και πραγματική διαθεσιμότητα στην Ελλάδα.'},
'packaging-food':{name:'Packaging & Food Production',title:'B2B συσκευασία & food production λύσεις',intro:'Vacuum packaging, sealing και παραγωγικός εξοπλισμός για επιχειρήσεις τροφίμων που θέλουν λιγότερα bottlenecks, επαναλήψεις και εργατοώρες.'},
'fleet-commercial':{name:'Fleet & Commercial Vehicles',title:'Fleet technology για επαγγελματικά οχήματα',intro:'TPMS, visibility και monitoring λύσεις για στόλους όπου downtime, ελαστικά, ασφάλεια και χρόνος εκτός δρομολογίου έχουν πραγματικό επιχειρηματικό κόστος.'},
'agriculture-automation':{name:'Agriculture Automation',title:'Αυτοματισμοί θερμοκηπίου & επαγγελματικής καλλιέργειας',intro:'Controllers, ventilation και monitoring για επιχειρήσεις που θέλουν λιγότερη χειροκίνητη παρέμβαση και καλύτερο έλεγχο κρίσιμων συνθηκών.'},
'workshop-diagnostics':{name:'Workshop & Diagnostics',title:'Επαγγελματικά διαγνωστικά & workshop productivity',intro:'Εργαλεία και συστήματα για συνεργεία που αξιολογούνται με βάση πραγματική συμβατότητα, δυνατότητες, υποστήριξη και συνολικό κόστος έναντι ελληνικών επιλογών.'},
'industrial-cleaning':{name:'Industrial Cleaning',title:'Επαγγελματικός καθαρισμός & productivity equipment',intro:'Εξοπλισμός καθαρισμού για εγκαταστάσεις και συνεργεία όπου ο χρόνος εργασίας, η απόδοση και η συντήρηση καθορίζουν το ROI.'}}
export const solutions={
'reduce-labour':{title:'Μείωσε εργατοώρες με B2B automation',intro:'Λύσεις όπου η χειροκίνητη επανάληψη είναι μετρήσιμο κόστος. Ο AFFINITY agent εξετάζει αν η αυτοματοποίηση λύνει πραγματικό bottleneck πριν προτείνει εξοπλισμό.',families:['Production & Processing','Packaging & Food Production','Agriculture Automation']},
'increase-throughput':{title:'Αύξησε throughput χωρίς λάθος επένδυση',intro:'Εξοπλισμός για παραγωγή και συσκευασία που πρέπει να διαστασιολογηθεί σωστά σε bottles/hour, batches/day ή units/hour.',families:['Production & Processing','Packaging & Food Production']},
'reduce-downtime':{title:'Μείωσε downtime σε στόλους και συνεργεία',intro:'Monitoring και diagnostic λύσεις για περιπτώσεις όπου η καθυστέρηση, η ακινησία ή η αργή διάγνωση έχει υψηλό λειτουργικό κόστος.',families:['Fleet & Commercial Vehicles','Workshop & Diagnostics']},
'automate-monitoring':{title:'Αυτοματοποίησε monitoring & control',intro:'Controllers και monitoring systems για επιχειρήσεις που χρειάζονται ταχύτερη αντίδραση, σταθερότερες συνθήκες και λιγότερο manual checking.',families:['Agriculture Automation','Fleet & Commercial Vehicles']},
'reduce-waste':{title:'Μείωσε waste και ασυνέπεια διαδικασιών',intro:'Packaging και processing λύσεις όπου η επαναληψιμότητα, το σωστό sealing ή η ομοιομορφία επηρεάζουν άμεσα κόστος και ποιότητα.',families:['Packaging & Food Production','Production & Processing']},
'find-missing-solution':{title:'Βρες επαγγελματική λύση που δεν βρίσκεις εύκολα στην Ελλάδα',intro:'Curated διεθνείς B2B λύσεις με exact/OEM/equivalent έλεγχο πριν χαρακτηριστούν πραγματικό Greek-market gap.',families:['Production & Processing','Packaging & Food Production','Fleet & Commercial Vehicles','Agriculture Automation','Workshop & Diagnostics','Industrial Cleaning']}}
