import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createRemoteJWKSet, jwtVerify } from 'npm:jose@6.1.0'
import postgres from 'https://deno.land/x/postgresjs@v3.4.5/mod.js'

const sql=postgres(Deno.env.get('SUPABASE_DB_URL')!,{prepare:false})
const embedder=new Supabase.ai.Session('gte-small')
const ISSUER='https://token.actions.githubusercontent.com'
const AUDIENCE='socialmarket-supabase-worker'
const REPOSITORY_ID='1329707883'
const REPOSITORY='vmoulakakis/Socialmarket'
const ALLOWED=new Set([
 'vmoulakakis/Socialmarket/.github/workflows/merchant-intelligence-v3.yml@refs/heads/main',
 'vmoulakakis/Socialmarket/.github/workflows/merchant-trust-research.yml@refs/heads/main'
])
const JWKS=createRemoteJWKSet(new URL(`${ISSUER}/.well-known/jwks`))
const clamp=(n:number,a=0,b=100)=>Math.max(a,Math.min(b,n))
const host=(u:string)=>{try{return new URL(u).hostname.toLowerCase().replace(/^www\./,'')}catch{return ''}}
function json(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json'}})}
async function auth(req:Request){const h=req.headers.get('authorization')||'';if(!h.startsWith('Bearer '))throw new Error('missing_oidc');const {payload}=await jwtVerify(h.slice(7),JWKS,{issuer:ISSUER,audience:AUDIENCE});if(String(payload.repository_id||'')!==REPOSITORY_ID||String(payload.repository||'')!==REPOSITORY||String(payload.ref||'')!=='refs/heads/main'||!ALLOWED.has(String(payload.workflow_ref||'')))throw new Error('oidc_not_allowed');return payload}
async function taxonomy(category:string,subcategory:string){const c=(category||'Other').trim().slice(0,120),cn=c.toLowerCase();let r=await sql`select id from catalog.taxonomy_nodes where node_type='category' and normalized_name=${cn} limit 1`;let cid=r[0]?.id;if(!cid){r=await sql`insert into catalog.taxonomy_nodes(node_type,name,normalized_name,slug) values('category',${c},${cn},${cn.replace(/[^a-z0-9]+/g,'-')+'-'+crypto.randomUUID().slice(0,6)}) returning id`;cid=r[0].id}let sid=cid;const s=(subcategory||'').trim().slice(0,120);if(s){const sn=s.toLowerCase();let q=await sql`select id from catalog.taxonomy_nodes where parent_id=${cid} and node_type='subcategory' and normalized_name=${sn} limit 1`;if(!q[0])q=await sql`insert into catalog.taxonomy_nodes(parent_id,node_type,name,normalized_name,slug) values(${cid},'subcategory',${s},${sn},${sn.replace(/[^a-z0-9]+/g,'-')+'-'+crypto.randomUUID().slice(0,6)}) returning id`;sid=q[0].id}return {cid,sid}}
async function claim(limit:number,worker:string){return await sql`with picked as (select id from ops.research_jobs where status='queued' and not_before<=now() and job_type='merchant_deep_research' order by priority desc,requested_at asc for update skip locked limit ${Math.max(1,Math.min(limit,60))}), upd as (update ops.research_jobs j set status='running',lease_owner=${worker},lease_expires_at=now()+interval '90 minutes',attempt_count=attempt_count+1 from picked p where j.id=p.id returning j.id,j.entity_id) select u.id job_id,m.* from upd u join catalog.merchants m on m.id=u.entity_id`}
async function authoritativeIdentity(merchantId:string){const r=await sql`select url,normalized_domain,confidence from evidence.source_links where entity_type='merchant' and entity_id=${merchantId} and is_authoritative=true and validation_status='validated' order by confidence desc,last_verified_at desc nulls last limit 1`;return r[0]||null}
async function persistEvidence(merchantId:string,items:any[]){let n=0;for(const e of (Array.isArray(items)?items:[]).slice(0,160)){const sourceKind=String(e.source_kind||e.type||'web_observation').slice(0,80);const url=e.source_url||e.url||null;const body=e.body||e.snippet||null;const title=e.title||null;const platform=e.platform||e.metadata?.platform||null;const collector=String(e.collector||e.metadata?.collector||'github_v4').slice(0,80);const confidence=clamp(Number(e.confidence??0.55),0,1);const hash=String(e.content_hash||await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${sourceKind}|${url||''}|${title||''}|${body||''}`)).then(b=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')));await sql`insert into evidence.observations(entity_type,entity_id,source_kind,platform,source_url,source_domain,collector,title,body,metrics,metadata,confidence,validation_status,content_hash) values('merchant',${merchantId},${sourceKind},${platform},${url},${host(url||'')||null},${collector},${title},${body},${sql.json(e.metrics||{})},${sql.json(e.metadata||{})},${confidence},${confidence>=0.7?'validated':'pending'},${hash}) on conflict(entity_type,entity_id,source_kind,content_hash) do update set collected_at=now(),confidence=greatest(evidence.observations.confidence,excluded.confidence),metadata=evidence.observations.metadata||excluded.metadata`;n++}return n}
async function save(d:any){const merchantId=String(d.merchant_id||''),jobId=String(d.job_id||'');if(!merchantId||!jobId)throw new Error('missing_ids');const authority=await authoritativeIdentity(merchantId);const effectiveUrl=authority?.url||d.official_url||null;const effectiveDomain=authority?.normalized_domain||d.official_domain||host(effectiveUrl||'')||null;if(authority&&d.official_url&&host(d.official_url)!==String(authority.normalized_domain||'')){d.metadata={...(d.metadata||{}),identity_contradiction:{research_url:d.official_url,authoritative_url:authority.url}}}
 const demand=clamp(Number(d.demand_score||0)),competition=clamp(Number(d.competition_score||0)),pain=clamp(Number(d.pain_gap_score||0)),sat=clamp(Number(d.satisfaction_score||50)),trust=clamp(Number(d.trust_score||50)),seo=clamp(Number(d.seo_technical_score||0)),conf=clamp(Number(d.confidence||0),0,1);let opp=clamp(demand*.35+pain*.40+(100-competition)*.20+sat*.05);if(trust<35)opp=Math.min(opp,45);const t=await taxonomy(String(d.category||'Other'),String(d.subcategory||''));const persisted=await persistEvidence(merchantId,d.evidence||[]);
 await sql`insert into intel.merchant_site_snapshots(merchant_id,official_url,resolved_domain,http_status,title,meta_description,detected_language,seo_technical_score,satisfaction_score,complaint_risk_score,trust_score,category_candidates,subcategory_candidates,pain_signals,competitor_domains,evidence,confidence,metadata) values(${merchantId},${effectiveUrl},${effectiveDomain},${d.http_status||null},${d.site_title||null},${d.site_description||null},${d.site_language||null},${seo},${sat},${clamp(Number(d.complaint_risk_score??100-sat))},${trust},${sql.json(d.category_candidates||[])},${sql.json(d.subcategory_candidates||[])},${sql.json(d.pain_evidence||[])},${sql.json(d.competitors||[])},${sql.json(d.evidence||[])},${conf},${sql.json({source:'github_searxng',version:'v4.1',raw:d.metadata||{},persisted_evidence:persisted})})`;
 await sql`insert into intel.category_market_snapshots(taxonomy_id,demand_score,competition_score,pain_gap_score,satisfaction_score,opportunity_score,confidence,demand_evidence,competition_evidence,pain_evidence,metadata) values(${t.sid},${demand},${competition},${pain},${sat},${opp},${conf},${sql.json(d.demand_evidence||[])},${sql.json(d.competition_evidence||[])},${sql.json(d.pain_evidence||[])},${sql.json({merchant_id:merchantId,source:'github_searxng'})})`;
 await sql`insert into intel.merchant_taxonomy_snapshots(merchant_id,taxonomy_id,is_primary,coverage_score,relevance_score,competition_score,greek_demand_fit_score,pain_gap_score,satisfaction_score,opportunity_score,semantic_relevance_score,confidence,evidence_count,metadata) values(${merchantId},${t.sid},true,${clamp(Number(d.coverage_score||80))},${clamp(Number(d.relevance_score||85))},${competition},${demand},${pain},${sat},${opp},${clamp(Number(d.semantic_relevance_score||85))},${conf},${Number(d.evidence_count||0)},${sql.json({methodology:'greek_gap_v4.1',source:'github_searxng'})})`;
 await sql`insert into intel.merchant_research_snapshots(merchant_id,official_domain,business_identity_score,review_reputation_score,review_footprint_score,complaint_risk_score,seo_technical_score,seo_organic_visibility_score,seo_brand_serp_score,competition_intensity_score,greek_market_fit_score,trust_score,deep_research_score,confidence,risk_flag,risk_reason,ai_summary,strengths,weaknesses,competitors,category_hints,evidence_count,methodology_version,metadata) values(${merchantId},${effectiveDomain},${clamp(Number(d.business_identity_score||50))},${sat},${clamp(Number(d.review_footprint_score||0))},${clamp(Number(d.complaint_risk_score??100-sat))},${seo},${clamp(Number(d.seo_organic_visibility_score||0))},${clamp(Number(d.seo_brand_serp_score||0))},${competition},${demand},${trust},${opp},${conf},${Boolean(d.risk_flag)},${d.risk_reason||null},${String(d.summary||`Demand ${demand}; competition ${competition}; pain gap ${pain}; satisfaction ${sat}; opportunity ${opp}.`).slice(0,1800)},${sql.json(d.strengths||[])},${sql.json(d.weaknesses||[])},${sql.json(d.competitors||[])},${sql.json(d.category_candidates||[])},${Number(d.evidence_count||0)},'merchant_research_v4.1',${sql.json(d.metadata||{})})`;
 await sql`update catalog.merchants set official_url=${effectiveUrl},official_domain=${effectiveDomain},site_title=${d.site_title||null},site_description=${d.site_description||null},site_language=${d.site_language||null},site_last_crawled_at=now(),primary_category=${d.category||'Other'},primary_subcategory=${d.subcategory||null},category_confidence=${conf},updated_at=now() where id=${merchantId}`;
 const sem=String(d.semantic_text||[d.merchant_name,d.category,d.subcategory,d.site_title,d.site_description,`Greek demand ${demand}`,`competition ${competition}`,`pain gap ${pain}`,`satisfaction ${sat}`,`trust ${trust}`].filter(Boolean).join(' | ')).slice(0,3500);const emb=await embedder.run(sem,{mean_pool:true,normalize:true});await sql`update ai.semantic_objects set semantic_text=${sem},embedding_model='gte-small',embedding_dimensions=384,embedding_gte=${JSON.stringify(emb)}::extensions.vector,embedding_status='ready',embedded_at=now(),updated_at=now(),metadata=metadata||${sql.json({category:d.category,subcategory:d.subcategory,opportunity_score:opp,source:'github_searxng_v4.1'})} where object_type='merchant' and object_id=${merchantId}`;
 await sql`update ops.research_jobs set status='completed',completed_at=now(),lease_owner=null,lease_expires_at=null,last_error=null where id=${jobId} and entity_id=${merchantId}`;return {merchant_id:merchantId,opportunity_score:opp,persisted_evidence:persisted,official_url:effectiveUrl}}
Deno.serve(async(req)=>{if(req.method==='GET')return json({ok:true,service:'merchant-research-gateway',version:'4.1'});if(req.method!=='POST')return json({error:'method_not_allowed'},405);try{const claims=await auth(req);const b=await req.json();const action=String(b.action||'');if(action==='claim')return json({ok:true,jobs:await claim(Number(b.limit||40),String(b.worker||'github-evidence-v4')),workflow_ref:claims.workflow_ref});if(action==='save')return json({ok:true,result:await save(b.result||{})});if(action==='fail'){await sql`update ops.research_jobs set status=case when attempt_count>=4 then 'failed' else 'queued' end,last_error=${String(b.error||'worker_failed').slice(0,1200)},lease_owner=null,lease_expires_at=null,not_before=now()+interval '30 minutes' where id=${String(b.job_id||'')}`;return json({ok:true})}throw new Error('action_not_allowed')}catch(e){console.error(e);return json({error:String(e instanceof Error?e.message:e)},401)}})
