'use client';

import {useEffect,useMemo,useState} from 'react';
import {motion} from 'motion/react';
import {supabase} from '@/lib/supabase';
import EChart from '@/components/analytics/EChart';
import styles from './demand.module.css';

const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const fmt=(v,d=0)=>finite(v)?Number(v).toLocaleString('el-GR',{maximumFractionDigits:d}):'—';
const pct=v=>finite(v)?`${fmt(Number(v)*(Number(v)<=1?100:1),0)}%`:'—';
const label=x=>x?.subcategory_name||x?.category_name||x?.taxonomy_name||'Unclassified';
const list=v=>Array.isArray(v)?v:[];
const truthTone=x=>({OBSERVED:'observed',DERIVED:'derived',INFERRED:'derived',FORECASTED:'modeled',CAUSAL_CANDIDATE:'withheld',WITHHELD:'withheld',UNAVAILABLE:'withheld'}[String(x||'').toUpperCase()]||'derived');
const palette={text:'#e9eef7',muted:'#7f8ba0',line:'rgba(148,163,184,.16)',violet:'#8b5cf6',cyan:'#22d3ee',emerald:'#34d399',amber:'#fbbf24',red:'#fb7185'};

function Truth({children,tone='DERIVED'}){return <span className={styles.truthChip} data-tone={truthTone(tone)}>{children||tone}</span>}
function Stat({label,value,meta,tone='violet'}){return <div className={styles.stat}><span>{label}</span><strong data-tone={tone}>{value}</strong><small>{meta}</small></div>}
function Scene({index,eyebrow,title,aside,children,className=''}){return <section className={`${styles.scene} ${className}`}><header className={styles.sceneHead}><div className={styles.sceneIndex}>{String(index).padStart(2,'0')}</div><div><span>{eyebrow}</span><h2>{title}</h2></div>{aside&&<aside>{aside}</aside>}</header>{children}</section>}
function Empty({code='WITHHELD',title,children}){return <div className={styles.emptyVisual}><span>{code}</span><b>{title}</b><p>{children}</p></div>}
function ErrorBox({children}){return children?<div className={styles.error}>{children}</div>:null}

export default function DemandIntelligence(){
 const [snapshot,setSnapshot]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [taxonomyId,setTaxonomyId]=useState(''),[category,setCategory]=useState('All');
 const [deep,setDeep]=useState(null),[contextBusy,setContextBusy]=useState(false),[aiBusy,setAiBusy]=useState(false);

 async function authFetch(url,options={}){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Admin session expired. Sign in again.');return fetch(url,{...options,headers:{...(options.headers||{}),authorization:`Bearer ${session.access_token}`,'content-type':'application/json'}})}
 async function load(){setLoading(true);setError('');try{const r=await authFetch('/api/admin-dashboard');const j=await r.json();if(!r.ok||j?.error)throw new Error(j?.error||`HTTP ${r.status}`);setSnapshot(j);const first=(j?.category_market||[]).find(x=>x.taxonomy_id);if(first&&!taxonomyId)setTaxonomyId(first.taxonomy_id)}catch(e){setError(String(e.message||e))}finally{setLoading(false)}}
 async function loadContext(id=taxonomyId){if(!id)return;setContextBusy(true);setError('');try{const r=await authFetch('/api/demand-intelligence',{method:'POST',body:JSON.stringify({action:'context',taxonomy_id:id,limit:120})});const j=await r.json();if(!r.ok||j?.error)throw new Error(j?.detail||j?.error||`HTTP ${r.status}`);setDeep(j)}catch(e){setError(String(e.message||e))}finally{setContextBusy(false)}}
 async function runAI(){if(!taxonomyId)return;setAiBusy(true);setError('');try{const r=await authFetch('/api/demand-intelligence',{method:'POST',body:JSON.stringify({action:'analyze',taxonomy_id:taxonomyId,limit:120})});const j=await r.json();if(!r.ok||j?.error)throw new Error(j?.detail||j?.error||`HTTP ${r.status}`);setDeep(j);if(j.ai_error)setError(`AI analysis unavailable: ${j.ai_error}`)}catch(e){setError(String(e.message||e))}finally{setAiBusy(false)}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(taxonomyId)loadContext(taxonomyId)},[taxonomyId]);

 const all=list(snapshot?.category_market);
 const cats=useMemo(()=>['All',...new Set(all.map(x=>x.category_name||x.taxonomy_name).filter(Boolean))],[all]);
 const rows=useMemo(()=>all.filter(x=>category==='All'||(x.category_name||x.taxonomy_name)===category),[all,category]);
 const selected=all.find(x=>String(x.taxonomy_id)===String(taxonomyId))||null;
 const det=deep?.deterministic||{},ctx=deep?.context||{},ai=deep?.analysis||null;
 const evidence=list(ctx.retrieved_evidence),supply=list(ctx.supply_context),pains=list(ctx.validated_pains),history=list(ctx.history);
 const eq=det.evidence_quality||{},sd=det.supply||{},fuzzy=det.fuzzy_state||{},white=det.fuzzy_whitespace||{},causal=det.causal_skeptic||{},gate=det.forecast_gate||{};

 const scatter=useMemo(()=>({backgroundColor:'transparent',grid:{left:52,right:28,top:30,bottom:52},xAxis:{name:'Competition →',min:0,max:100,nameLocation:'middle',nameGap:34,axisLabel:{color:palette.muted},splitLine:{lineStyle:{color:'rgba(148,163,184,.07)'}}},yAxis:{name:'Demand →',min:0,max:100,nameLocation:'middle',nameGap:39,axisLabel:{color:palette.muted},splitLine:{lineStyle:{color:'rgba(148,163,184,.07)'}}},tooltip:{backgroundColor:'#0b1220',borderColor:palette.line,textStyle:{color:palette.text},formatter:p=>`<b>${p.value[4]}</b><br/>Demand ${fmt(p.value[1])}<br/>Competition ${fmt(p.value[0])}<br/>Opportunity ${fmt(p.value[2])}<br/>Evidence ${fmt(p.value[3])}`},visualMap:{show:false,min:0,max:100,dimension:2,inRange:{color:['#475569','#22d3ee','#8b5cf6','#34d399']}},series:[{type:'scatter',data:rows.filter(x=>finite(x.demand_score)&&finite(x.competition_score)).map(x=>[Number(x.competition_score),Number(x.demand_score),Number(x.opportunity_score||0),Number(x.evidence_entities||0),label(x),x.taxonomy_id]),symbolSize:v=>Math.max(12,Math.min(42,12+Math.sqrt(Math.max(0,v[3]))*3)),itemStyle:{opacity:.82,borderColor:'rgba(255,255,255,.28)',borderWidth:1},emphasis:{scale:1.18}}]}),[rows]);

 const regime=useMemo(()=>({backgroundColor:'transparent',grid:{left:52,right:30,top:34,bottom:55},xAxis:{name:'Derived solution coverage →',min:0,max:100,nameLocation:'middle',nameGap:35,axisLabel:{color:palette.muted},splitLine:{lineStyle:{color:'rgba(148,163,184,.07)'}}},yAxis:{name:'Canonical demand →',min:0,max:100,nameLocation:'middle',nameGap:40,axisLabel:{color:palette.muted},splitLine:{lineStyle:{color:'rgba(148,163,184,.07)'}}},tooltip:{backgroundColor:'#0b1220',borderColor:palette.line,textStyle:{color:palette.text},formatter:p=>`Demand <b>${fmt(p.value[1])}</b><br/>Supply strength ${fmt(p.value[0])}<br/>Whitespace ${fmt(p.value[2],1)}`},series:[{type:'scatter',data:finite(selected?.demand_score)&&finite(sd.analytical_supply_strength)?[[Number(sd.analytical_supply_strength),Number(selected.demand_score),white.score||0]]:[],symbolSize:54,itemStyle:{color:palette.violet,borderColor:palette.cyan,borderWidth:2},markArea:{silent:true,label:{color:'rgba(226,232,240,.45)'},itemStyle:{opacity:.04},data:[[{name:'UNDER-SERVED',xAxis:0,yAxis:50,itemStyle:{color:palette.emerald}},{xAxis:50,yAxis:100}],[{name:'SUPPLIED DEMAND',xAxis:50,yAxis:50,itemStyle:{color:palette.amber}},{xAxis:100,yAxis:100}],[{name:'EMERGING',xAxis:0,yAxis:0,itemStyle:{color:palette.cyan}},{xAxis:50,yAxis:50}]]}}]}),[selected,sd,white]);

 const histOption=useMemo(()=>({backgroundColor:'transparent',grid:{left:45,right:18,top:28,bottom:42},tooltip:{trigger:'axis',backgroundColor:'#0b1220',borderColor:palette.line,textStyle:{color:palette.text}},legend:{top:0,textStyle:{color:palette.muted,fontSize:9}},xAxis:{type:'category',data:history.map(x=>String(x.observed_at||'').slice(5,16)),axisLabel:{color:palette.muted,fontSize:9,hideOverlap:true},axisLine:{lineStyle:{color:palette.line}}},yAxis:{type:'value',min:0,max:100,axisLabel:{color:palette.muted},splitLine:{lineStyle:{color:'rgba(148,163,184,.07)'}}},series:[{name:'Demand',type:'line',smooth:true,showSymbol:false,data:history.map(x=>x.demand_score),lineStyle:{color:palette.cyan,width:2},itemStyle:{color:palette.cyan}},{name:'Competition',type:'line',smooth:true,showSymbol:false,data:history.map(x=>x.competition_score),connectNulls:false,lineStyle:{color:palette.amber,width:1.4},itemStyle:{color:palette.amber}},{name:'Pain',type:'line',smooth:true,showSymbol:false,data:history.map(x=>x.pain_gap_score),connectNulls:false,lineStyle:{color:palette.violet,width:1.4},itemStyle:{color:palette.violet}}]}),[history]);

 const sourceOption=useMemo(()=>{
  const counts={};
  for(const e of evidence){const d=e.source_domain||'unknown';counts[d]=(counts[d]||0)+1}
  const data=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,12);
  return {backgroundColor:'transparent',grid:{left:130,right:20,top:8,bottom:28},xAxis:{type:'value',axisLabel:{color:palette.muted},splitLine:{lineStyle:{color:'rgba(148,163,184,.07)'}}},yAxis:{type:'category',inverse:true,data:data.map(x=>x[0]),axisLabel:{color:'#9ba8bb',fontSize:9,width:115,overflow:'truncate'}},series:[{type:'bar',data:data.map(x=>x[1]),barMaxWidth:15,itemStyle:{color:palette.cyan,borderRadius:[0,6,6,0]}}]};
 },[evidence]);

 if(loading)return <main className={styles.page}><div className={styles.loading}>Loading Greek market intelligence…</div></main>;
 const thesis=ai?.executive_thesis||null,panel=ai?.research_panel||{},decision=list(ai?.decision_board),scenes=list(ai?.presentation_scenes);
 return <main className={styles.page}>
  <motion.header className={styles.hero} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}>
   <div className={styles.heroCopy}><div className={styles.engineRow}><Truth tone="OBSERVED">PRODUCTION EVIDENCE</Truth><Truth tone="DERIVED">HYBRID RAG + GRAPH</Truth><Truth tone="INFERRED">FUZZY V3.1</Truth><Truth tone="WITHHELD">CAUSAL / NEURAL GATED</Truth></div><h1>Deep Greek Demand Intelligence</h1><p>Όχι ένα ακόμη score dashboard. Κάθε αγορά αναλύεται ως evidence → pain/JTBD → supply structure → demand–supply regime → temporal readiness → causal skepticism → business decision. Η προσφορά δεν επιτρέπεται να αλλοιώσει ποτέ το canonical Demand.</p></div>
   <div className={styles.heroActions}><select value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(x=><option key={x}>{x}</option>)}</select><select value={taxonomyId} onChange={e=>setTaxonomyId(e.target.value)}>{rows.filter(x=>x.taxonomy_id).map(x=><option key={x.taxonomy_id} value={x.taxonomy_id}>{label(x)}</option>)}</select><button onClick={()=>loadContext()} disabled={contextBusy}>{contextBusy?'Researching…':'↻ Refresh dossier'}</button><button className={styles.primary} onClick={runAI} disabled={aiBusy||contextBusy}>{aiBusy?'Deep research panel…':'✦ Deep AI Analysis'}</button></div>
  </motion.header>
  <ErrorBox>{error}</ErrorBox>

  <section className={styles.stats}>
   <Stat label="Canonical demand" value={fmt(selected?.demand_score)} meta="OBSERVED/DERIVED production index" tone="cyan"/>
   <Stat label="Competition" value={fmt(selected?.competition_score)} meta={finite(selected?.competition_score)?'production metric':'missing remains missing'} tone={finite(selected?.competition_score)?'amber':'red'}/>
   <Stat label="Validated pain" value={fmt(selected?.pain_gap_score)} meta={`${fmt(pains.length)} retrieved pain clusters`} tone="violet"/>
   <Stat label="Supply strength" value={fmt(sd.analytical_supply_strength,1)} meta={`${fmt(sd.merchant_count)} exact-taxonomy merchants`} tone="blue"/>
   <Stat label="Fuzzy whitespace" value={fmt(white.score,1)} meta={white.status||'UNAVAILABLE'} tone="emerald"/>
   <Stat label="Temporal history" value={fmt(gate?.history?.unique_days)} meta={`${fmt(gate?.history?.span_days,1)} day span · ${gate.status||'WITHHELD'}`} tone={gate.status==='WITHHELD'?'amber':'emerald'}/>
  </section>

  <Scene index={1} eyebrow="EXECUTIVE THESIS" title="What is the strongest defensible market thesis?" aside="Kimi-style: one decision statement, then evidence and uncertainty." className={styles.thesisScene}>
   <div className={styles.thesisGrid}><div><div className={styles.truthRow}><Truth tone={thesis?.truth_label||'DERIVED'}>{thesis?.truth_label||'DETERMINISTIC'}</Truth><Truth tone="OBSERVED">Demand {fmt(selected?.demand_score)}</Truth><Truth tone="INFERRED">Whitespace {fmt(white.score,1)}</Truth></div><h3>{thesis?.headline||`${label(selected)}: demand is ${finite(selected?.demand_score)?'measured':'not yet comparable'}, while exploitability remains a separate question`}</h3><p>{thesis?.summary||'Run Deep AI Analysis to synthesize the retrieved Greek evidence, validated pains, exact-taxonomy merchant supply, temporal diagnostics and skeptical alternatives into an executive thesis.'}</p></div><div className={styles.thesisFacts}><div><span>Evidence dossier</span><b>{fmt(eq.observations)} observations</b><small>{fmt(eq.independent_domains)} independent domains · HHI {fmt(eq.domain_hhi,2)}</small></div><div><span>Market state</span><b>{String(fuzzy.state||'uncertain').replaceAll('_',' ')}</b><small>fuzzy state is DERIVED, not observed</small></div><div><span>Causal status</span><b>{String(causal.status||'WITHHELD').replaceAll('_',' ')}</b><small>causality is never inferred from correlation</small></div></div></div>
  </Scene>

  <Scene index={2} eyebrow="DEMAND ANATOMY" title="What actually creates the demand thesis?" aside="Observed evidence is separated from inference and model commentary.">
   <div className={styles.sceneGrid2}><div>{list(ai?.demand_anatomy).length?<div className={styles.insightList}>{list(ai.demand_anatomy).map((x,i)=><div key={i}><Truth tone={x.classification}>{x.classification}</Truth><b>{x.dimension}</b><p>{x.assessment}</p><small>{x.limits}</small></div>)}</div>:<div className={styles.insightList}><div><Truth tone="OBSERVED">EVIDENCE</Truth><b>{fmt(eq.observations)} retrieved observations across {fmt(eq.independent_domains)} domains</b><p>Validated share {pct(eq.validated_share)} · mean retrieval {fmt(eq.mean_retrieval,2)} · authority {fmt(eq.mean_authority,2)}.</p></div><div><Truth tone="DERIVED">SOURCE CONCENTRATION</Truth><b>Domain HHI {fmt(eq.domain_hhi,2)}</b><p>High concentration weakens confidence even when raw evidence volume is large.</p></div></div>}</div><EChart option={sourceOption} height={360} ariaLabel="Evidence source concentration"/></div>
  </Scene>

  <Scene index={3} eyebrow="DEMAND × SUPPLY REGIME" title="Is demand under-served, crowded, or merely visible?" aside="Supply can reduce whitespace. It cannot reduce canonical demand.">
   <div className={styles.sceneGrid2}><EChart option={regime} height={430} ariaLabel="Demand versus derived supply strength"/><div><div className={styles.callout}><Truth tone="INFERRED">INFERRED WHITESPACE</Truth><b>{fmt(white.score,1)} · {String(fuzzy.state||'uncertain').replaceAll('_',' ')}</b><p>{ai?.demand_supply_regime?.interpretation||white.semantics||'The fuzzy engine combines demand, pain, real competition when available, supply strength and confidence to describe exploitability.'}</p><small>Canonical Demand remains exactly {fmt(white.canonical_demand_unchanged??selected?.demand_score)}.</small></div><div className={styles.insightList}>{list(white.rules).slice(0,6).map((r,i)=><div key={i}><Truth tone="INFERRED">RULE {i+1}</Truth><b>{r.rule}</b><p>Activation {fmt(r.activation,2)} → target whitespace {fmt(r.target)}</p></div>)}</div></div></div>
  </Scene>

  <Scene index={4} eyebrow="JOBS TO BE DONE" title="What outcome is the Greek buyer actually trying to achieve?" aside="JTBD facets come only from validated pain text; AI interpretation cannot invent evidence.">
   {list(ai?.research_panel?.jobs_to_be_done?.jobs).length?<div className={styles.sceneGrid3}>{list(ai.research_panel.jobs_to_be_done.jobs).slice(0,9).map((j,i)=><div className={styles.callout} key={i}><Truth tone="DERIVED">JTBD</Truth><b>{j.job}</b><p>{j.desired_outcome}</p><small>Constraints: {list(j.constraints).join(' · ')||'—'} · confidence {fmt(j.confidence_0_100)}%</small></div>)}</div>:det.jobs_to_be_done?.facets?.length?<div className={styles.sceneGrid3}>{det.jobs_to_be_done.facets.slice(0,9).map((j,i)=><div className={styles.callout} key={i}><Truth tone="DERIVED">LEXICAL JTBD</Truth><b>{j.facets.join(' · ')}</b><p>{j.text}</p></div>)}</div>:<Empty title="No validated JTBD evidence yet">Without validated pain clusters the system refuses to manufacture buyer jobs or constraints.</Empty>}
  </Scene>

  <div className={styles.sceneGrid2}>
   <Scene index={5} eyebrow="MARKET STRUCTURE" title="How credible and concentrated is solution supply?" aside="Exact taxonomy merchant coverage only."><div className={styles.supplySummary}><div><span>Merchants</span><b>{fmt(sd.merchant_count)}</b></div><div><span>Trust</span><b>{fmt(sd.avg_trust,1)}</b></div><div><span>Commercial</span><b>{fmt(sd.avg_commercial,1)}</b></div><div><span>Risk rate</span><b>{pct(sd.risk_rate)}</b></div></div><div className={styles.insightList} style={{marginTop:12}}>{supply.slice(0,8).map((m,i)=><div key={m.merchant_id||i}><b>{m.canonical_name||'Merchant'}</b><p>Trust {fmt(m.trust_score)} · commercial {fmt(m.commercial_score)} · research confidence {pct(m.research_confidence)}</p></div>)}</div></Scene>
   <Scene index={6} eyebrow="TEMPORAL REGIME" title="Is there enough history to call this a trend?" aside="No decorative trend if temporal depth is insufficient.">{history.length?<><EChart option={histOption} height={310} ariaLabel="Demand competition and pain history"/><div className={styles.historyMeta}><span>{fmt(gate?.history?.points)} points</span><span>{fmt(gate?.history?.unique_days)} unique days</span><span>{fmt(gate?.history?.span_days,1)} day span</span><span>{gate?.status||'WITHHELD'}</span></div></>:<Empty title="No temporal history exposed">Current observation is valid, but no trend claim can be made.</Empty>}</Scene>
  </div>

  <Scene index={7} eyebrow="FORECAST MODEL LAB" title="Which models are scientifically allowed to speak?" aside="Naive/statistical baselines first. Neural challengers only after history and rolling-backtest gates.">
   <div className={styles.forecastLab}><div><span>Descriptive</span><b>{gate?.temporal_tiers?.descriptive?'READY':'WITHHELD'}</b><p>Current state and observed changes only.</p></div><div><span>Statistical shadow</span><b>{gate?.temporal_tiers?.statistical_shadow?'ELIGIBLE':'WITHHELD'}</b><p>AutoETS · Theta · AutoARIMA after sufficient daily depth.</p></div><div><span>Neural shadow</span><b>{gate?.temporal_tiers?.neural_shadow?'ELIGIBLE':'WITHHELD'}</b><p>NHITS first; NBEATSx/PatchTST/TFT only as challengers.</p></div></div><div className={styles.callout}><Truth tone="WITHHELD">PRODUCTION FORECAST</Truth><b>{ai?.forecast_lab?.production_forecast||gate.status||'WITHHELD'}</b><p>{ai?.forecast_lab?.why||gate.rule||'A model is not promoted because it is sophisticated. It must beat chronological baselines and preserve uncertainty calibration.'}</p></div>
  </Scene>

  <Scene index={8} eyebrow="EVIDENCE GRAPH" title="Can the thesis be traced back to actual evidence?" aside="GraphRAG structure = lineage, not demand strength.">
   <div className={styles.sceneGrid2}><div className={styles.thesisFacts}><div><span>Graph nodes</span><b>{fmt(det.graph_rag?.summary?.node_count)}</b><small>{fmt(det.graph_rag?.summary?.edge_count)} auditable relations</small></div><div><span>Independent domains</span><b>{fmt(det.graph_rag?.summary?.independent_domains)}</b><small>domain HHI {fmt(det.graph_rag?.summary?.domain_hhi,2)}</small></div><div><span>Explicit contradictions</span><b>{fmt(det.graph_rag?.summary?.explicit_contradictions)}</b><small>absence is not treated as contradiction</small></div></div><div className={styles.insightList}>{evidence.slice(0,7).map((e,i)=><div key={e.id||i}><Truth tone={e.validation_status==='validated'?'OBSERVED':'DERIVED'}>{e.source_kind||'EVIDENCE'}</Truth><b>{e.title||e.source_domain||'Evidence'}</b><p>{String(e.body||'').slice(0,220)}</p><small>{e.source_domain||'—'} · retrieval {fmt(e.retrieval?.score,2)}</small></div>)}</div></div>
  </Scene>

  <Scene index={9} eyebrow="CAUSAL SKEPTIC" title="What else could explain the apparent demand?" aside="The system attempts to falsify the story before acting.">
   <div className={styles.sceneGrid2}><div className={styles.insightList}>{list(panel?.causal_skeptic?.alternative_explanations).length?list(panel.causal_skeptic.alternative_explanations).map((x,i)=><div key={i}><Truth tone="CAUSAL_CANDIDATE">ALTERNATIVE {i+1}</Truth><b>{x.hypothesis}</b><p>{x.why_plausible}</p><small>{x.evidence_or_test}</small></div>):list(causal.alternative_explanations).map((x,i)=><div key={i}><Truth tone="CAUSAL_CANDIDATE">HYPOTHESIS</Truth><b>{x.hypothesis}</b><p>{x.why}</p></div>)}</div><div className={styles.callout}><Truth tone="WITHHELD">CAUSAL STATUS</Truth><b>{causal.status||'WITHHELD'}</b><p>Required: explicit DAG, treatment/outcome, aligned exogenous controls, identification, placebo/data-subset refutation and sensitivity analysis.</p><small>Correlation remains non-causal until those gates pass.</small></div></div>
  </Scene>

  <Scene index={10} eyebrow="DECISION BOARD" title="What should we do now — and what would change the decision?" aside="Action follows evidence quality, not presentation confidence.">
   {decision.length?<div className={styles.sceneGrid3}>{decision.slice(0,9).map((d,i)=><div className={styles.callout} key={i}><Truth tone={d.decision==='PROMOTE'?'OBSERVED':'INFERRED'}>{d.decision}</Truth><b>{d.priority} · {d.action}</b><p>{d.why}</p><small>Need: {d.evidence_needed||'—'} · watch {d.metric_to_watch||'—'} · confidence {fmt(d.confidence_0_100)}%</small></div>)}</div>:<Empty code="AI PANEL OPTIONAL" title="Run Deep AI Analysis for an audited decision board">Deterministic research remains available now; the AI panel adds synthesis, falsification and evidence-collection priorities without changing canonical metrics.</Empty>}
  </Scene>

  {scenes.length>0&&<Scene index="+" eyebrow="PRESENTATION COMPILER" title="AI-generated analytical scene plan" aside="The same research object can drive executive reports, future exports and interactive presentations."><div className={styles.sceneGrid3}>{scenes.slice(0,10).map((s,i)=><div className={styles.callout} key={i}><Truth tone={s.truth_label}>{s.truth_label}</Truth><b>{s.order}. {s.headline||s.title}</b><p>{s.question}</p><small>{s.visual_type} · {s.so_what} · Action: {s.action}</small></div>)}</div></Scene>}

  <Scene index="A" eyebrow="AUDITABLE MARKET UNIVERSE" title="Canonical rows remain visible beneath every story" aside="Click a row to open its complete deep dossier."><div className={styles.tableWrap}><table><thead><tr><th>Category</th><th>Subcategory</th><th>Demand</th><th>Competition</th><th>Pain</th><th>Opportunity</th><th>Confidence</th><th>Evidence</th></tr></thead><tbody>{rows.map(x=><tr key={x.taxonomy_id} data-selected={String(x.taxonomy_id)===String(taxonomyId)} onClick={()=>x.taxonomy_id&&setTaxonomyId(x.taxonomy_id)}><td><b>{x.category_name||x.taxonomy_name||'—'}</b></td><td>{x.subcategory_name||'Category level'}</td><td>{fmt(x.demand_score)}</td><td>{fmt(x.competition_score)}</td><td>{fmt(x.pain_gap_score)}</td><td><b>{fmt(x.opportunity_score)}</b></td><td>{pct(x.confidence)}</td><td>{fmt(x.evidence_entities)}</td></tr>)}</tbody></table></div></Scene>

  <Scene index="M" eyebrow="MARKET MAP" title="Where demand and competition are simultaneously measurable" aside="Missing competition rows are intentionally excluded, never placed at zero.">{rows.some(x=>finite(x.demand_score)&&finite(x.competition_score))?<EChart option={scatter} height={520} ariaLabel="Greek demand competition map"/>:<Empty title="No comparable demand/competition rows">The system will not manufacture a quadrant position from missing competition.</Empty>}</Scene>
  <footer className={styles.footer}>Deep Demand Intelligence V3.1 · Production truth only · Demand ≠ Supply · Missing ≠ zero · Forecast ≠ observation · Correlation ≠ causation</footer>
 </main>;
}
