'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
import styles from './optimization.module.css';

const n=(v,d=0)=>v===null||v===undefined||Number.isNaN(Number(v))?'—':Number(v).toLocaleString('el-GR',{maximumFractionDigits:d});
const money=(v,d=2)=>v===null||v===undefined||Number.isNaN(Number(v))?'—':`€${Number(v).toLocaleString('el-GR',{minimumFractionDigits:d,maximumFractionDigits:d})}`;
const pct=(v,d=2)=>v===null||v===undefined?'—':`${n(v,d)}%`;
const signalLabel={scale_candidate:'Scale candidate',approval_risk:'Approval risk',payout_limited:'Payout limited',funnel_opportunity:'Funnel opportunity',high_priority:'High priority',monitor:'Monitor'};
const signalTone={scale_candidate:styles.good,approval_risk:styles.bad,payout_limited:styles.warn,funnel_opportunity:styles.info,high_priority:styles.good,monitor:styles.muted};

function Kpi({label,value,sub}){return <div className={styles.kpi}><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Empty({children}){return <div className={styles.empty}>{children}</div>}
function MiniBar({value,label}){return <div className={styles.mini}><div><span>{label}</span><b>{n(value,1)}</b></div><i><em style={{width:`${Math.max(0,Math.min(100,Number(value||0)))}%`}}/></i></div>}

export default function Optimization(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [selectedId,setSelectedId]=useState(''),[dailyClicks,setDailyClicks]=useState(100),[paidCpc,setPaidCpc]=useState(''),[organicCost,setOrganicCost]=useState(0),[paidCreativeCost,setPaidCreativeCost]=useState(0),[organicAdj,setOrganicAdj]=useState(0),[paidAdj,setPaidAdj]=useState(0);
 const [brief,setBrief]=useState(null),[aiBusy,setAiBusy]=useState(false),[query,setQuery]=useState('');
 async function load(){setLoading(true);setError('');const {data,error}=await supabase.rpc('admin_affiliate_optimization_snapshot');if(error)setError(error.message);else{setData(data);const first=(data.reaction_queue||[])[0]||(data.program_performance||[])[0];if(first&&!selectedId)setSelectedId(first.program_id)}setLoading(false)}
 useEffect(()=>{load()},[]);
 const programs=data?.program_performance||[];
 const selected=useMemo(()=>programs.find(x=>x.program_id===selectedId)||programs[0]||null,[programs,selectedId]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?programs.filter(x=>`${x.merchant_name} ${x.program_name} ${x.primary_category||''}`.toLowerCase().includes(q)):programs},[programs,query]);
 const sim=useMemo(()=>{
   if(!selected)return null;
   const clicks=Math.max(0,Number(dailyClicks)||0),cr=Math.max(0,Number(selected.conversion_rate)||0),approval=Math.max(0,Math.min(100,Number(selected.approval_rate)||0)),epc=Math.max(0,Number(selected.epc)||0);
   const calc=(adj,cost)=>{const cvr=cr*(1+(Number(adj)||0)/100),conv=clicks*cvr/100,approved=conv*approval/100,epcValue=epc*clicks/100,conservative=epcValue*approval/100,net=conservative-cost;return{cvr,conv,approved,epcValue,conservative,cost,net,roi:cost>0?net/cost*100:null}};
   const organic=calc(organicAdj,Math.max(0,Number(organicCost)||0));
   const paidCost=paidCpc===''?null:Math.max(0,Number(paidCpc)||0)*clicks+Math.max(0,Number(paidCreativeCost)||0);
   const paid=paidCost===null?null:calc(paidAdj,paidCost);
   const horizons=[7,30,90].map(days=>({days,clicks:clicks*days,conversions:organic.conv*days,approved:organic.approved*days,epcValue:organic.epcValue*days,conservative:organic.conservative*days,organicNet:organic.net*days,paidNet:paid?paid.net*days:null}));
   return{clicks,cr,approval,epc,organic,paid,horizons,assumptions:{daily_clicks:clicks,paid_cpc_eur:paidCpc===''?null:Number(paidCpc),organic_content_cost_per_day_eur:Number(organicCost)||0,paid_creative_cost_per_day_eur:Number(paidCreativeCost)||0,organic_cvr_adjustment_pct:Number(organicAdj)||0,paid_cvr_adjustment_pct:Number(paidAdj)||0,epc_basis:'network displayed EPC normalized per 100 clicks for scenario arithmetic',selected_program_id:selected.program_id}};
 },[selected,dailyClicks,paidCpc,organicCost,paidCreativeCost,organicAdj,paidAdj]);
 async function analyze(){if(!data)return;setAiBusy(true);setError('');try{const {data:{session}}=await supabase.auth.getSession();const r=await fetch('https://rpfadpdnnxequgvdcfoq.supabase.co/functions/v1/admin-intelligence-gateway',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${session?.access_token||''}`},body:JSON.stringify({action:'optimization_brief',optimization:data,simulation:sim})});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||`HTTP ${r.status}`);setBrief(j.optimization);await supabase.rpc('admin_save_affiliate_optimization_run',{p_mode:'ai_brief',p_assumptions:sim?.assumptions||{},p_result:j.optimization||{}})}catch(e){setError(String(e.message||e))}finally{setAiBusy(false)}}
 async function saveSim(){if(!sim)return;const {error}=await supabase.rpc('admin_save_affiliate_optimization_run',{p_mode:'simulation',p_assumptions:sim.assumptions,p_result:sim});if(error)setError(error.message)}
 if(loading)return <main className={styles.wrap}><div className={styles.loading}>Loading affiliate optimization intelligence…</div></main>;
 const c=data?.data_coverage||{},k=data?.network_kpi_summary||{},fp=data?.first_party_totals_30d||{};
 return <main className={styles.wrap}>
  <header className={styles.hero}><div><span className={styles.eyebrow}>360° Affiliate Optimization</span><h1>Optimize</h1><p>Merchant performance, conversion economics, A/B simulations, channel hypotheses, profitability and fast reaction signals — grounded in production evidence.</p></div><div className={styles.actions}><button onClick={load}>↻ Refresh</button><button className={styles.primary} onClick={analyze} disabled={aiBusy}>{aiBusy?'AI optimizing…':'✦ AI 360° Optimize'}</button></div></header>
  {error&&<div className={styles.error}>{error}</div>}
  <section className={styles.truth}><div><b>{n(c.network_program_snapshots)}</b><span>network program baselines</span></div><div><b>{n(c.network_programs_with_conversion)}</b><span>with CVR</span></div><div><b>{n(c.network_programs_with_epc)}</b><span>with EPC</span></div><div><b>{n(c.first_party_metric_rows_30d)}</b><span>first-party rows · 30d</span></div><p className={c.first_party_metric_rows_30d>0?styles.good:styles.warn}>{c.first_party_metric_rows_30d>0?'First-party mode available':'Network-baseline mode: no SocialMarket click/conversion history yet'}</p></section>

  <section className={styles.kpis}>
   <Kpi label="Median network CVR" value={pct(k.median_conversion_rate,3)} sub={`avg ${pct(k.avg_conversion_rate,3)}`}/>
   <Kpi label="Median network EPC" value={n(k.median_epc,2)} sub={`avg ${n(k.avg_epc,2)} · network display`}/>
   <Kpi label="Median approval" value={pct(k.median_approval_rate,2)} sub={`avg ${pct(k.avg_approval_rate,2)}`}/>
   <Kpi label="Validated pains" value={n(c.validated_pain_clusters)} sub={`${n(c.evidence_observations)} evidence observations`}/>
   <Kpi label="Our approved conversions · 30d" value={n(fp.conversions_approved)} sub={`${n(fp.outbound_clicks)} outbound clicks`}/>
   <Kpi label="Our approved commission · 30d" value={money(fp.commission_approved_eur)} sub={`${money(fp.media_spend_eur)} media spend`}/>
  </section>

  <section className={styles.grid2}>
   <div className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>A/B conversion simulator</span><h2>Organic vs Paid</h2></div><button onClick={saveSim}>Save scenario</button></div>
    <label className={styles.selectLabel}>Merchant program<select value={selected?.program_id||''} onChange={e=>setSelectedId(e.target.value)}>{programs.slice(0,300).map(x=><option key={x.program_id} value={x.program_id}>{x.merchant_name} · {x.program_name}</option>)}</select></label>
    {selected&&<div className={styles.baseline}><span>Observed network baseline</span><b>CVR {pct(selected.conversion_rate)} · EPC {n(selected.epc,2)} · Approval {pct(selected.approval_rate)} · Rank {n(selected.rank_score,1)}</b><small>{selected.primary_category||'Unclassified'} · confidence {pct(selected.data_confidence,0)}</small></div>}
    <div className={styles.inputs}><label>Daily affiliate clicks<input type="number" min="0" value={dailyClicks} onChange={e=>setDailyClicks(e.target.value)}/></label><label>Paid CPC €<input type="number" min="0" step="0.01" placeholder="enter real/target CPC" value={paidCpc} onChange={e=>setPaidCpc(e.target.value)}/></label><label>Organic cost/day €<input type="number" min="0" step="0.01" value={organicCost} onChange={e=>setOrganicCost(e.target.value)}/></label><label>Paid creative/day €<input type="number" min="0" step="0.01" value={paidCreativeCost} onChange={e=>setPaidCreativeCost(e.target.value)}/></label><label>Organic CVR adjustment %<input type="number" step="1" value={organicAdj} onChange={e=>setOrganicAdj(e.target.value)}/></label><label>Paid CVR adjustment %<input type="number" step="1" value={paidAdj} onChange={e=>setPaidAdj(e.target.value)}/></label></div>
    {sim&&<div className={styles.ab}><div><span>Variant A · Organic</span><strong>{n(sim.organic.approved,2)} approved conv/day</strong><small>scenario CVR {pct(sim.organic.cvr)} · conservative EPC value/day {money(sim.organic.conservative)} · net {money(sim.organic.net)}</small></div><div><span>Variant B · Paid</span>{sim.paid?<><strong>{n(sim.paid.approved,2)} approved conv/day</strong><small>scenario CVR {pct(sim.paid.cvr)} · cost/day {money(sim.paid.cost)} · net {money(sim.paid.net)} · ROI {pct(sim.paid.roi,1)}</small></>:<><strong>Cost input required</strong><small>Enter a paid CPC before profitability can be compared. No CPC is invented.</small></>}</div></div>}
   </div>
   <div className={styles.panel}><span className={styles.eyebrow}>Scenario forecast</span><h2>7 / 30 / 90 days</h2><p className={styles.note}>Traffic volume is your input. Conversion behavior uses the observed network program baseline; this is not a causal forecast.</p>{sim?.horizons.map(h=><div className={styles.horizon} key={h.days}><b>{h.days}d</b><div><span>Clicks</span><strong>{n(h.clicks)}</strong></div><div><span>Conversions</span><strong>{n(h.conversions,1)}</strong></div><div><span>Approved</span><strong>{n(h.approved,1)}</strong></div><div><span>Conservative EPC value</span><strong>{money(h.conservative)}</strong></div><div><span>Organic net</span><strong>{money(h.organicNet)}</strong></div><div><span>Paid net</span><strong>{h.paidNet===null?'CPC needed':money(h.paidNet)}</strong></div></div>)}</div>
  </section>

  <section className={styles.grid2}>
   <div className={styles.panel}><span className={styles.eyebrow}>Quick reactions</span><h2>Opportunity queue</h2>{(data?.reaction_queue||[]).slice(0,14).map(x=><button className={styles.reaction} key={x.program_id} onClick={()=>setSelectedId(x.program_id)}><div><b>{x.merchant_name}</b><small>{x.program_name} · {x.primary_category||'—'}</small></div><div><span className={signalTone[x.reaction_signal]}>{signalLabel[x.reaction_signal]}</span><small>CVR {pct(x.conversion_rate)} · EPC {n(x.epc,2)} · appr. {pct(x.approval_rate)}</small></div></button>)}{!(data?.reaction_queue||[]).length&&<Empty>No reaction signals.</Empty>}</div>
   <div className={styles.panel}><span className={styles.eyebrow}>Channel truth</span><h2>Evidence & publishing readiness</h2><p className={styles.note}>Evidence volume indicates where demand/pain observations were found. It does not equal conversion performance.</p>{(data?.channel_evidence||[]).map(x=><div className={styles.channel} key={x.platform}><div><b>{x.platform}</b><small>{n(x.validated)} validated · confidence {x.avg_confidence===null?'—':pct(Number(x.avg_confidence)*100,0)}</small></div><strong>{n(x.observations)}</strong></div>)}<h3>Publishing outbox</h3>{(data?.publishing_by_platform||[]).map(x=><div className={styles.channel} key={x.platform}><div><b>{x.platform}</b><small>{n(x.published)} published · {n(x.failed)} failed</small></div><strong>{n(x.total)}</strong></div>)}</div>
  </section>

  <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>Merchant / program performance</span><h2>Affiliate KPI leaderboard</h2></div><input className={styles.search} placeholder="Search merchant/program…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className={styles.tableWrap}><table><thead><tr><th>Merchant</th><th>Signal</th><th>CVR</th><th>EPC</th><th>Approval</th><th>Approval days</th><th>Commercial</th><th>Demand</th><th>Competition</th><th>Trust</th><th>Rank</th></tr></thead><tbody>{filtered.slice(0,120).map(x=><tr key={x.program_id} onClick={()=>setSelectedId(x.program_id)} className={selected?.program_id===x.program_id?styles.activeRow:''}><td><b>{x.merchant_name}</b><small>{x.program_name}</small></td><td><span className={signalTone[x.reaction_signal]}>{signalLabel[x.reaction_signal]}</span></td><td>{pct(x.conversion_rate)}</td><td>{n(x.epc,2)}</td><td>{pct(x.approval_rate)}</td><td>{n(x.approval_days,1)}</td><td>{n(x.commercial_score,1)}</td><td>{n(x.merchant_demand_score,1)}</td><td>{n(x.merchant_competition_score,1)}</td><td>{n(x.merchant_trust_score,1)}</td><td><b>{n(x.rank_score,1)}</b></td></tr>)}</tbody></table></div></section>

  <section className={styles.grid2}>
   <div className={styles.panel}><span className={styles.eyebrow}>Product profitability</span><h2>Per-product conversion economics</h2>{(data?.product_profitability||[]).length?<div className={styles.tableWrap}><table><thead><tr><th>Product</th><th>Merchant</th><th>Commission</th><th>CVR</th><th>Approved /100 clicks</th><th>Approved € /100 clicks</th><th>Break-even CPC</th><th>Opportunity</th></tr></thead><tbody>{data.product_profitability.slice(0,60).map(x=><tr key={x.offer_id}><td>{x.canonical_title}</td><td>{x.merchant_name}</td><td>{money(x.expected_commission_eur)}</td><td>{pct(x.network_conversion_rate)}</td><td>{n(x.expected_approved_conversions_per_100_clicks,2)}</td><td>{money(x.expected_approved_commission_per_100_clicks)}</td><td>{money(x.break_even_cpc_eur,4)}</td><td>{n(x.final_opportunity_score,1)}</td></tr>)}</tbody></table></div>:<Empty>0 validated products currently exist. Product profitability will populate automatically after Product Intelligence persists validated offers.</Empty>}</div>
   <div className={styles.panel}><span className={styles.eyebrow}>Success KPI model</span><h2>What determines a winning affiliate promotion?</h2><div className={styles.kpiModel}><div><b>Demand fit</b><span>validated pain + Greek demand + intent</span></div><div><b>Merchant economics</b><span>CVR + EPC + commission + approval</span></div><div><b>Traffic efficiency</b><span>outbound CTR + CPC + own EPC</span></div><div><b>Conversion quality</b><span>approved CVR + reversal/rejection rate</span></div><div><b>Profitability</b><span>approved commission − media/content cost</span></div><div><b>Speed</b><span>approval days + freshness + reaction latency</span></div><div><b>Scale safety</b><span>ROI + confidence + source diversity</span></div><div><b>Creative learning</b><span>A/B lift with enough first-party evidence</span></div></div></div>
  </section>

  {brief&&<section className={`${styles.panel} ${styles.ai}`}><div className={styles.panelHead}><div><span className={styles.eyebrow}>AI 360° decision layer</span><h2>{brief.executive_decision||'Optimization brief'}</h2></div><span>confidence {n(brief.confidence_0_100)}%</span></div><div className={styles.grid2}><div><h3>Best opportunities</h3>{(brief.best_opportunities||[]).map((x,i)=><div className={styles.aiItem} key={i}><b>{x.merchant} · {x.program}</b><span>{x.signal}</span><small>{x.why}</small></div>)}</div><div><h3>Funnel strategy</h3>{(brief.funnel_strategy||[]).map((x,i)=><div className={styles.aiItem} key={i}><b>{x.priority} · {x.channel}</b><span>{x.funnel}</span><small>{x.why}</small></div>)}</div></div><div className={styles.grid2}><div><h3>A/B tests</h3>{(brief.ab_tests||[]).map((x,i)=><div className={styles.aiItem} key={i}><b>{x.hypothesis}</b><span>A: {x.variant_a}</span><span>B: {x.variant_b}</span><small>Primary KPI: {x.primary_kpi} · Rule: {x.decision_rule}</small></div>)}</div><div><h3>Quick reactions</h3>{(brief.quick_reactions||[]).map((x,i)=><div className={styles.aiItem} key={i}><b>{x.trigger}</b><span>{x.action}</span><small>{x.why}</small></div>)}</div></div></section>}

  <section className={styles.method}><b>Data truth:</b> Linkwise/network CVR, EPC and approval are observed merchant-program baselines. Demand/pain comes from stored evidence and audited semantic intelligence. A/B numbers are simulations from your explicit traffic/cost assumptions. No generic CTR/CPC or invented conversions are inserted. Network EPC is used as displayed and normalized per 100 clicks only inside the scenario arithmetic; once first-party earnings/clicks exist, own EPC becomes authoritative.
  </section>
 </main>
}
