'use client';

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

export default function Products(){
  const [rows,setRows]=useState([]);
  const [loading,setLoading]=useState(true);
  useEffect(()=>{(async()=>{
    const {data}=await supabase.from('opportunity_scores')
      .select('id,higo_adjusted,higo_raw,confidence,demand_score,forecast_momentum_score,attention_gap_score,purchase_ease_score,offer_score,merchant_reliability_score,decision,skeptic_status,seller_competition_score,ad_pressure_score,competition_kill,validity_runway_score,products(id,product_name,price,full_price,discount_pct,category_raw,brand_name,merchant_name,program_name,image_url,tracking_url,purchase_friction,valid_to,validity_days_remaining,market_eligible,merchant_trust_score,is_preferred_offer,duplicate_group_size,canonical_group_key)')
      .neq('decision','DROP').eq('competition_kill',false).order('higo_adjusted',{ascending:false}).limit(250);
    setRows((data||[]).filter(x=>x.products?.market_eligible!==false&&x.products?.is_preferred_offer!==false));setLoading(false);
  })()},[]);
  return <main><div className="hero"><div><div className="eyebrow">Opportunity selection</div><h1>Product Candidates</h1><p className="sub">€150+, valid_to &gt;20 ημέρες, χωρίς travel, χωρίς high competition και μόνο η preferred offer όταν το ίδιο προϊόν υπάρχει σε πολλούς merchants.</p></div></div><div className="card">{loading?<p className="muted">Loading candidates…</p>:rows.length===0?<p className="muted">Δεν υπάρχουν candidates ακόμη. Πρέπει πρώτα να ολοκληρωθούν import → merchant resolution → niche discovery → market intelligence.</p>:<table className="table"><thead><tr><th>Product</th><th>Merchant</th><th>Price</th><th>Validity</th><th>Demand</th><th>Forecast</th><th>Seller Comp.</th><th>Ad Pressure*</th><th>Confidence</th><th>HIGO</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td>{o.products?.product_name||'—'}<div className="muted">{o.products?.category_raw||o.products?.brand_name||''}</div></td><td><strong>{o.products?.merchant_name||'—'}</strong><div className="muted">trust {Number(o.products?.merchant_trust_score??o.merchant_reliability_score??0).toFixed(0)} · {Number(o.products?.duplicate_group_size||1)} offer{o.products?.duplicate_group_size===1?'':'s'}</div></td><td>{o.products?.price?`€${Number(o.products.price).toFixed(2)}`:'—'}<div className="muted">{o.products?.discount_pct!=null?`${Number(o.products.discount_pct).toFixed(0)}% off`:''}</div></td><td>{o.products?.validity_days_remaining!=null?`${o.products.validity_days_remaining}d`:'—'}<div className="muted">runway {Number(o.validity_runway_score||0).toFixed(0)}</div></td><td>{Number(o.demand_score).toFixed(0)}</td><td>{Number(o.forecast_momentum_score).toFixed(0)}</td><td>{Number(o.seller_competition_score||0).toFixed(0)}</td><td>{Number(o.ad_pressure_score||0).toFixed(0)}</td><td>{Math.round(Number(o.confidence)*100)}%</td><td className={Number(o.higo_adjusted)>=92?'score good':Number(o.higo_adjusted)>=85?'score warn':'score'}>{Number(o.higo_adjusted).toFixed(1)}</td></tr>)}</tbody></table>}<p className="muted" style={{marginTop:14}}>* Ad Pressure είναι evidence-labelled proxy μέχρι να συνδεθεί direct paid-ad source. Merchant Trust σήμερα βασίζεται σε feed/offer evidence· υπάρχει έτοιμο πεδίο για external reputation enrichment.</p></div></main>
}
