import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import {createRemoteJWKSet,jwtVerify} from 'npm:jose@6.1.0'
const ISSUER='https://token.actions.githubusercontent.com',AUDIENCE='socialmarket-supabase-worker',REPOSITORY_ID='1329707883',REPOSITORY='vmoulakakis/Socialmarket'
const ALLOWED=new Set(['vmoulakakis/Socialmarket/.github/workflows/semantic-marketplace-200.yml@refs/heads/main'])
const JWKS=createRemoteJWKSet(new URL(`${ISSUER}/.well-known/jwks`))
const DEEPSEEK_KEY=Deno.env.get('DEEPSEEK_API_KEY')||Deno.env.get('DEEP_SEEK_API_KEY')||'',DEEPSEEK_MODEL=Deno.env.get('DEEPSEEK_MODEL')||'deepseek-v4-pro'
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}})
async function auth(req:Request){const h=req.headers.get('authorization')||'';if(!h.startsWith('Bearer '))throw new Error('missing_oidc');const {payload}=await jwtVerify(h.slice(7),JWKS,{issuer:ISSUER,audience:AUDIENCE});if(String(payload.repository_id||'')!==REPOSITORY_ID||String(payload.repository||'')!==REPOSITORY||String(payload.ref||'')!=='refs/heads/main'||!ALLOWED.has(String(payload.workflow_ref||'')))throw new Error('oidc_not_allowed')}
async function structured(system:string,payload:unknown,maxTokens:number){if(!DEEPSEEK_KEY)throw new Error('deepseek_not_configured');const run=async(retry=false)=>{const body={model:DEEPSEEK_MODEL,thinking:{type:'disabled'},reasoning_effort:'low',temperature:0.02,max_tokens:retry?Math.min(maxTokens+250,2200):maxTokens,response_format:{type:'json_object'},messages:[{role:'system',content:system},{role:'user',content:`Return ONE complete compact JSON object only. No prose. ${retry?'Use shorter strings. ':''}Input:\n${JSON.stringify(payload)}`}]};const r=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${DEEPSEEK_KEY}`},body:JSON.stringify(body)});const raw=await r.text();if(!r.ok)throw new Error(`deepseek_${r.status}:${raw.slice(0,500)}`);const j=JSON.parse(raw),choice=j?.choices?.[0]||{},content=String(choice?.message?.content||'');if(!content.trim())throw new Error(`deepseek_empty:${String(choice?.finish_reason||'unknown')}`);if(String(choice.finish_reason||'')==='length')throw new Error('deepseek_truncated');return JSON.parse(content)};try{return await run(false)}catch(first){try{return await run(true)}catch(second){throw new Error(`structured_output_failed:${String(first).slice(0,160)}|retry:${String(second).slice(0,220)}`)}}}
const CLUSTER_SCHEMA=`Cluster fields: cluster_key short ASCII; niche; subniche; job_to_be_done Greek <=70 chars; pain_statement Greek <=80; gap_statement Greek <=80; demand_score,whitespace_score,commercial_intent_score,confidence 0-100; evidence_ids[] only supplied IDs max3; rationale Greek <=70; search_queries[] exactly3 phrases <=6 words.`
const LINK_PLAN=`AFFINITY Linkwise Opportunity Cartographer for Greece. Pick exactly ONE opportunity cluster, not a product. Use only supplied evidence; never invent metrics. It MUST be distinct from excluded_cluster_keys and broad enough for materially different products from trustworthy merchants. Return {"linkwise_clusters":[one cluster]}. ${CLUSTER_SCHEMA}`
const ALI_PLAN=`AFFINITY AliExpress Opportunity Cartographer for Greece. Pick exactly ONE useful problem-solving opportunity cluster, not novelty and not a product. Use only supplied evidence; never invent metrics. It MUST be distinct from excluded_cluster_keys and suitable for exact/OEM/equivalent Greek scarcity research. Return {"aliexpress_clusters":[one cluster]}. ${CLUSTER_SCHEMA}`
const RESEARCH_SYSTEM=`AFFINITY Product Research Agent for Greece. Deterministic gates already passed. Use only supplied facts; missing evidence is not proof. Never invent reviews, orders, warranty, shipping, features, certification, market size, search volume or conversion. Return {"items":[...]}. For each source_record_hash return only: source_record_hash; demand_score,pain_score,whitespace_score,scarcity_score,semantic_fit_score,product_quality_score,organic_score,ads_score,viral_score,affinity_score 0-100; greek_availability_assessment ABSENT|VERY_RARE|AVAILABLE|FUNCTIONAL_EQUIVALENT_EXISTS|UNKNOWN; solution_statement Greek <=90; semantic_tags[] 3-5; research_reason Greek <=90; quality_evidence[] max3; quality_unknowns[] max2; landing_candidate boolean.`
const SKEPTIC_SYSTEM=`AFFINITY Skeptic QA. Try to reject each candidate using only evidence + Research output. Check unsupported claims, identity/quality weakness, Greek exact/OEM/equivalents, merchant/seller weakness, fake novelty, variants, logistics, safety/regulatory risk, weak pain fit and contradictions. Return {"items":[...]}. For each source_record_hash return only: source_record_hash; verdict validated|needs_review|rejected; corrected_greek_availability ABSENT|VERY_RARE|AVAILABLE|FUNCTIONAL_EQUIVALENT_EXISTS|UNKNOWN; product_quality_score 0-100; contradiction_score 0-100; reasons[] max3 short; blockers[] max3; required_rechecks[] max2.`
Deno.serve(async req=>{if(req.method==='GET')return json({ok:true,service:'marketplace200-ai-gateway',version:'1.4-atomic-agents',model:DEEPSEEK_MODEL,architecture:'atomic-planner-compact-qa-thinking-disabled'});if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);try{await auth(req);const b=await req.json(),action=String(b.action||''),payload=b.payload||{};if(action==='plan_linkwise')return json({ok:true,plan:await structured(LINK_PLAN,payload,850)});if(action==='plan_aliexpress')return json({ok:true,plan:await structured(ALI_PLAN,payload,850)});if(action==='research')return json({ok:true,research:await structured(RESEARCH_SYSTEM,payload,2100)});if(action==='skeptic')return json({ok:true,skeptic:await structured(SKEPTIC_SYSTEM,payload,1700)});throw new Error('action_not_allowed')}catch(e){const m=String(e instanceof Error?e.message:e);console.error(e);return json({ok:false,error:m},m.includes('oidc')?401:500)}})
