-- Autonomous affiliate social engine: Postiz-first/Buffer-fallback publishing,
-- public TikTok link-in-bio redirects, click analytics, incidents and provider health.

create table if not exists public.affiliate_redirects (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  product_id uuid references public.products(id) on delete cascade,
  platform text not null check (platform in ('facebook','instagram','tiktok','linkedin')),
  tracking_url_snapshot text not null,
  label text not null,
  merchant_name text,
  price numeric(14,2),
  image_url text,
  active boolean not null default true,
  valid_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_affiliate_redirects_active_platform on public.affiliate_redirects(platform, active, created_at desc);

create table if not exists public.affiliate_click_events (
  id bigint generated by default as identity primary key,
  redirect_id uuid references public.affiliate_redirects(id) on delete set null,
  slug text not null,
  platform text,
  referrer text,
  user_agent_hash text,
  request_fingerprint text,
  clicked_at timestamptz not null default now()
);
create index if not exists idx_affiliate_click_events_slug_time on public.affiliate_click_events(slug, clicked_at desc);

create table if not exists public.social_publish_jobs (
  id uuid primary key default gen_random_uuid(),
  calendar_item_id uuid not null unique references public.social_content_calendar(id) on delete cascade,
  platform text not null check (platform in ('facebook','instagram','tiktok','linkedin')),
  preferred_provider text not null default 'auto' check (preferred_provider in ('auto','postiz','buffer')),
  actual_provider text,
  status text not null default 'queued' check (status in ('queued','processing','scheduled','published','failed','cancelled')),
  attempt_count integer not null default 0,
  idempotency_key text not null unique,
  external_post_id text,
  external_url text,
  provider_payload jsonb not null default '{}'::jsonb,
  provider_response jsonb not null default '{}'::jsonb,
  error text,
  worker_id text,
  next_attempt_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_social_publish_jobs_queue on public.social_publish_jobs(status, next_attempt_at, created_at);

create table if not exists public.social_incidents (
  id uuid primary key default gen_random_uuid(),
  severity text not null default 'warning' check (severity in ('info','warning','critical')),
  incident_type text not null,
  platform text,
  provider text,
  entity_type text,
  entity_id text,
  message text not null,
  details jsonb not null default '{}'::jsonb,
  status text not null default 'open' check (status in ('open','acknowledged','resolved')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists idx_social_incidents_open on public.social_incidents(status, severity, last_seen_at desc);

create table if not exists public.social_provider_health (
  provider text not null,
  platform text not null,
  configured boolean not null default false,
  healthy boolean not null default false,
  details jsonb not null default '{}'::jsonb,
  checked_at timestamptz not null default now(),
  primary key(provider, platform)
);

create table if not exists public.product_csv_import_batches (
  id uuid primary key default gen_random_uuid(),
  file_name text,
  rows_seen integer not null default 0,
  rows_upserted integer not null default 0,
  rows_rejected integer not null default 0,
  status text not null default 'completed',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.affiliate_redirects enable row level security;
alter table public.affiliate_click_events enable row level security;
alter table public.social_publish_jobs enable row level security;
alter table public.social_incidents enable row level security;
alter table public.social_provider_health enable row level security;
alter table public.product_csv_import_batches enable row level security;

do $$ declare t text; begin
  foreach t in array array['affiliate_redirects','social_publish_jobs','social_incidents','social_provider_health','product_csv_import_batches'] loop
    execute format('drop policy if exists admin_authenticated_all on public.%I', t);
    execute format('create policy admin_authenticated_all on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;

drop policy if exists public_active_affiliate_redirects on public.affiliate_redirects;
create policy public_active_affiliate_redirects on public.affiliate_redirects for select to anon
  using (active = true and (valid_until is null or valid_until > now()));

drop policy if exists public_insert_affiliate_clicks on public.affiliate_click_events;
create policy public_insert_affiliate_clicks on public.affiliate_click_events for insert to anon
  with check (char_length(slug) between 3 and 120);

drop policy if exists admin_affiliate_clicks on public.affiliate_click_events;
create policy admin_affiliate_clicks on public.affiliate_click_events for select to authenticated using (true);

-- Generated campaign creatives are public marketing assets by design. This gives Buffer/Postiz permanent non-expiring media URLs.
update storage.buckets set public = true where id = 'creatives';

insert into public.app_settings(key,value,updated_at) values (
  'autonomous_social_engine',
  '{"enabled":true,"min_price_eur":100,"requested_products":10,"horizon_days":30,"auto_publish":true,"min_higo":70,"min_confidence":0.55,"min_creative_quality":80,"publisher_mode":"hybrid","platforms":["facebook","instagram","tiktok","linkedin"]}'::jsonb,
  now()
) on conflict (key) do update set value=excluded.value,updated_at=now();

update public.app_settings
set value=jsonb_set(coalesce(value,'{}'::jsonb),'{min_price_eur}','100'::jsonb,true),updated_at=now()
where key='selection_rules';

create or replace function public.claim_social_publish_jobs(p_worker_id text,p_limit integer default 20)
returns setof public.social_publish_jobs
language plpgsql security definer set search_path=public
as $$
begin
  return query
  with picked as (
    select id from public.social_publish_jobs
    where status in ('queued','failed') and next_attempt_at<=now() and attempt_count<5
    order by next_attempt_at,created_at
    for update skip locked
    limit greatest(1,least(coalesce(p_limit,20),100))
  )
  update public.social_publish_jobs j
  set status='processing',worker_id=p_worker_id,attempt_count=j.attempt_count+1,
      started_at=coalesce(j.started_at,now()),updated_at=now(),error=null
  where j.id in (select id from picked)
  returning j.*;
end;
$$;
revoke all on function public.claim_social_publish_jobs(text,integer) from public,anon,authenticated;
grant execute on function public.claim_social_publish_jobs(text,integer) to service_role;
