-- VMDB v16: canonical SocialMarket -> SocialScheduler publishing contract.
-- This replaces the deleted legacy Supabase publishing control plane while keeping
-- SocialScheduler's existing RPC/Edge Function contract stable.

create extension if not exists pgcrypto;

create table if not exists public.social_publishing_outbox (
  id uuid primary key default gen_random_uuid(),
  source_key text not null unique,
  source_presentation_id uuid references public.social_presentation_intelligence(id) on delete set null,
  platform text not null check (platform in ('facebook','instagram','tiktok','linkedin')),
  title text,
  brand_slug text,
  brand_name text,
  caption text not null,
  hashtags jsonb not null default '[]'::jsonb,
  format text not null default 'post',
  media_url text,
  tracking_url text,
  scheduled_for timestamptz not null,
  priority integer not null default 100,
  status text not null default 'queued' check (status in ('queued','leased','scheduled','published','failed','cancelled')),
  provider_key text,
  claimed_by text,
  claimed_at timestamptz,
  lease_expires_at timestamptz,
  external_post_id text,
  external_permalink text,
  scheduled_at timestamptz,
  published_at timestamptz,
  attempt_count integer not null default 0,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists social_publishing_outbox_ready_idx
  on public.social_publishing_outbox(status, scheduled_for, priority, created_at);
create index if not exists social_publishing_outbox_platform_idx
  on public.social_publishing_outbox(platform, status, scheduled_for);
create index if not exists social_publishing_outbox_provider_idx
  on public.social_publishing_outbox(provider_key, status, scheduled_for);

create table if not exists public.social_distribution_metrics (
  id bigint generated by default as identity primary key,
  outbox_id uuid references public.social_publishing_outbox(id) on delete set null,
  provider_key text,
  platform text,
  metric_payload jsonb not null,
  observed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create or replace function public.social_outbox_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_social_publishing_outbox_updated_at on public.social_publishing_outbox;
create trigger trg_social_publishing_outbox_updated_at
before update on public.social_publishing_outbox
for each row execute function public.social_outbox_touch_updated_at();

create or replace function public.vmdb_social_outbox_refill(p_hours integer default 72)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inserted integer := 0;
  v_pending integer := 0;
  v_hours integer := greatest(12, least(coalesce(p_hours,72),168));
begin
  insert into public.social_publishing_outbox(
    source_key, source_presentation_id, platform, title, brand_slug, brand_name,
    caption, hashtags, format, media_url, tracking_url, scheduled_for, priority, metadata
  )
  select
    'presentation:' || s.id::text,
    s.id,
    lower(s.platform),
    coalesce(nullif(s.creative_brief->>'title',''), nullif(s.hook,''), 'Approved SocialMarket content'),
    coalesce(nullif(s.creative_brief->>'brand_slug',''),'socialmarket'),
    coalesce(nullif(s.creative_brief->>'brand_name',''),'SocialMarket'),
    coalesce(
      nullif(s.creative_brief->>'caption',''),
      nullif(concat_ws(E'\n\n', nullif(s.hook,''), nullif(s.pain_statement,''), nullif(s.solution_statement,''), nullif(s.value_statement,''), nullif(s.cta,'')),''),
      'Approved SocialMarket content'
    ),
    case when jsonb_typeof(s.creative_brief->'hashtags')='array' then s.creative_brief->'hashtags' else '[]'::jsonb end,
    coalesce(nullif(s.creative_brief->>'format',''),'post'),
    nullif(s.creative_brief->>'media_url',''),
    nullif(s.creative_brief->>'tracking_url',''),
    (s.creative_brief->>'scheduled_for')::timestamptz,
    greatest(1, least(coalesce(nullif(s.creative_brief->>'priority','')::integer,100),1000)),
    jsonb_build_object(
      'vmdb_source','social_presentation_intelligence',
      'confidence',s.confidence,
      'critic_status',s.critic_status,
      'product_candidate_id',s.product_candidate_id,
      'merchant_id',s.merchant_id,
      'problem_cluster_id',s.problem_cluster_id
    )
  from public.social_presentation_intelligence s
  where lower(s.platform) in ('facebook','instagram','tiktok','linkedin')
    and lower(coalesce(s.critic_status,'')) in ('approved','pass','passed','ready')
    and coalesce(s.creative_brief->>'scheduled_for','') ~ '^\d{4}-\d{2}-\d{2}T'
    and (s.creative_brief->>'scheduled_for')::timestamptz > now()
    and (s.creative_brief->>'scheduled_for')::timestamptz <= now() + make_interval(hours => v_hours)
    and nullif(s.creative_brief->>'tracking_url','') is not null
    and (
      lower(s.platform) not in ('instagram','tiktok')
      or nullif(s.creative_brief->>'media_url','') is not null
    )
  on conflict (source_key) do nothing;

  get diagnostics v_inserted = row_count;
  select count(*) into v_pending
  from public.social_publishing_outbox
  where status='queued' and scheduled_for > now();

  return jsonb_build_object('inserted',v_inserted,'pending',v_pending,'horizon_hours',v_hours,'source','vmdb');
end;
$$;

create or replace function public.social_outbox_release_expired_leases()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare v_count integer;
begin
  update public.social_publishing_outbox
     set status='queued', claimed_by=null, claimed_at=null, lease_expires_at=null, provider_key=null
   where status='leased' and lease_expires_at is not null and lease_expires_at < now();
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function public.worker_v2_outbox_health()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_released integer;
  v_queued integer;
  v_leased integer;
  v_scheduled integer;
  v_published integer;
  v_failed integer;
begin
  v_released := public.social_outbox_release_expired_leases();
  select
    count(*) filter(where status='queued'),
    count(*) filter(where status='leased'),
    count(*) filter(where status='scheduled'),
    count(*) filter(where status='published'),
    count(*) filter(where status='failed')
  into v_queued,v_leased,v_scheduled,v_published,v_failed
  from public.social_publishing_outbox;
  return jsonb_build_object(
    'source','vmdb','released_expired_leases',v_released,
    'queued',v_queued,'leased',v_leased,'scheduled',v_scheduled,'published',v_published,'failed',v_failed
  );
end;
$$;

create or replace function public.worker_v2_outbox_peek(p_limit integer default 10)
returns setof public.social_publishing_outbox
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.social_outbox_release_expired_leases();
  return query
  select o.*
  from public.social_publishing_outbox o
  where o.status='queued'
    and o.scheduled_for > now()
  order by o.priority asc, o.scheduled_for asc, o.created_at asc
  limit greatest(1,least(coalesce(p_limit,10),50));
end;
$$;

create or replace function public.social_outbox_claim_provider(
  p_provider_key text,
  p_executor text,
  p_capacity jsonb,
  p_lease_minutes integer default 30
)
returns setof public.social_publishing_outbox
language plpgsql
security definer
set search_path = public
as $$
declare
  v_platform text;
  v_limit integer;
  v_lease integer := greatest(5,least(coalesce(p_lease_minutes,30),120));
begin
  if lower(coalesce(p_provider_key,'')) not in ('buffer','postzen','brightbean') then
    raise exception 'invalid_provider';
  end if;
  perform public.social_outbox_release_expired_leases();

  foreach v_platform in array array['facebook','instagram','tiktok','linkedin'] loop
    v_limit := greatest(0,least(coalesce(nullif(p_capacity->>v_platform,'')::integer,0),20));
    if v_limit > 0 then
      return query
      with picked as (
        select o.id
        from public.social_publishing_outbox o
        where o.status='queued'
          and o.platform=v_platform
          and o.scheduled_for > now()
          and (o.provider_key is null or o.provider_key=lower(p_provider_key))
        order by o.priority asc, o.scheduled_for asc, o.created_at asc
        for update skip locked
        limit v_limit
      )
      update public.social_publishing_outbox o
         set status='leased',
             provider_key=lower(p_provider_key),
             claimed_by=coalesce(nullif(p_executor,''),'socialscheduler-'||lower(p_provider_key)),
             claimed_at=now(),
             lease_expires_at=now()+make_interval(mins=>v_lease),
             attempt_count=o.attempt_count+1
      from picked p
      where o.id=p.id
      returning o.*;
    end if;
  end loop;
end;
$$;

create or replace function public.socialscheduler_claim_provider_capacity(
  p_provider_key text,
  p_executor text,
  p_capacity jsonb,
  p_lease_minutes integer default 30
)
returns setof public.social_publishing_outbox
language sql
security definer
set search_path = public
as $$
  select * from public.social_outbox_claim_provider(p_provider_key,p_executor,p_capacity,p_lease_minutes);
$$;

create or replace function public.worker_v3_outbox_claim_capacity(
  p_executor text,
  p_capacity jsonb,
  p_lease_minutes integer default 30
)
returns setof public.social_publishing_outbox
language sql
security definer
set search_path = public
as $$
  select * from public.social_outbox_claim_provider('buffer',p_executor,p_capacity,p_lease_minutes);
$$;

create or replace function public.worker_v2_outbox_claim(
  p_executor text,
  p_limit integer default 10,
  p_lease_minutes integer default 30
)
returns setof public.social_publishing_outbox
language plpgsql
security definer
set search_path = public
as $$
declare
  v_capacity jsonb;
  v_limit integer := greatest(1,least(coalesce(p_limit,10),50));
begin
  v_capacity := jsonb_build_object('facebook',v_limit,'instagram',v_limit,'tiktok',v_limit,'linkedin',v_limit);
  return query select * from public.social_outbox_claim_provider('buffer',p_executor,v_capacity,p_lease_minutes) limit v_limit;
end;
$$;

create or replace function public.worker_v3_outbox_refill(p_hours integer default 72)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select public.vmdb_social_outbox_refill(p_hours);
$$;

create or replace function public.worker_v3_outbox_ack(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid := nullif(p_payload->>'job_id','')::uuid;
  v_status text := lower(coalesce(p_payload->>'status',''));
  v_row public.social_publishing_outbox%rowtype;
begin
  if v_id is null then raise exception 'job_id_required'; end if;
  if v_status not in ('scheduled','published','failed','cancelled','queued') then
    raise exception 'invalid_status';
  end if;

  update public.social_publishing_outbox o
     set status=v_status,
         external_post_id=coalesce(nullif(p_payload->>'external_post_id',''),o.external_post_id),
         external_permalink=coalesce(nullif(p_payload->>'external_permalink',''),o.external_permalink),
         scheduled_at=case when v_status='scheduled' then coalesce(nullif(p_payload->>'scheduled_at','')::timestamptz,o.scheduled_for,now()) else o.scheduled_at end,
         published_at=case when v_status='published' then coalesce(nullif(p_payload->>'published_at','')::timestamptz,now()) else o.published_at end,
         last_error=case when v_status='failed' then nullif(p_payload->>'error','') else null end,
         metadata=o.metadata || coalesce(p_payload->'metadata','{}'::jsonb),
         claimed_by=null,
         claimed_at=null,
         lease_expires_at=null
   where o.id=v_id
   returning o.* into v_row;

  if not found then raise exception 'job_not_found'; end if;
  return to_jsonb(v_row);
end;
$$;

create or replace function public.worker_v3_delivery_metrics_batch(p_rows jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_count integer := 0;
begin
  if jsonb_typeof(p_rows) <> 'array' then raise exception 'rows_array_required'; end if;
  insert into public.social_distribution_metrics(outbox_id,provider_key,platform,metric_payload,observed_at)
  select
    case when coalesce(x->>'job_id','') ~* '^[0-9a-f-]{36}$' then (x->>'job_id')::uuid else null end,
    nullif(lower(x->>'provider_key'),''),
    nullif(lower(x->>'platform'),''),
    x,
    coalesce(nullif(x->>'observed_at','')::timestamptz,now())
  from jsonb_array_elements(p_rows) x;
  get diagnostics v_count = row_count;
  return jsonb_build_object('accepted',v_count,'source','vmdb');
end;
$$;

create or replace function public.worker_v3_optimize_week(p_week_start text)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object('ok',true,'week_start',p_week_start,'mode','vmdb_learning_pipeline','mutations',0);
$$;

create or replace function public.worker_v2_outbox_reconcile(p_limit integer default 200)
returns setof public.social_publishing_outbox
language sql
security definer
set search_path = public
as $$
  select o.* from public.social_publishing_outbox o
  where o.status in ('scheduled','failed','leased')
  order by o.updated_at desc
  limit greatest(1,least(coalesce(p_limit,200),500));
$$;

create or replace function public.socialscheduler_provider_reconcile_candidates(p_provider text,p_limit integer default 100)
returns setof public.social_publishing_outbox
language sql
security definer
set search_path = public
as $$
  select o.* from public.social_publishing_outbox o
  where o.provider_key=lower(p_provider)
    and o.status in ('scheduled','leased','failed')
  order by o.updated_at desc
  limit greatest(1,least(coalesce(p_limit,100),500));
$$;

create or replace function public.worker_v11_delivery_reconcile(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid := null;
  v_provider text := lower(coalesce(p_payload->>'provider_key',''));
  v_status text := lower(coalesce(p_payload->>'status',''));
  v_target text;
  v_row public.social_publishing_outbox%rowtype;
begin
  if v_provider not in ('buffer','postzen','brightbean') then raise exception 'invalid_provider'; end if;
  if coalesce(p_payload->>'job_id','') ~* '^[0-9a-f-]{36}$' then v_id := (p_payload->>'job_id')::uuid; end if;
  if v_id is null then raise exception 'job_id_required'; end if;
  v_target := case
    when v_status in ('published','sent','success','succeeded') then 'published'
    when v_status in ('scheduled','queued','pending') then 'scheduled'
    when v_status in ('failed','error','cancelled') then 'failed'
    else null
  end;
  if v_target is null then
    select * into v_row from public.social_publishing_outbox where id=v_id;
    if not found then raise exception 'job_not_found'; end if;
    return to_jsonb(v_row) || jsonb_build_object('reconciliation','unknown_state_no_mutation');
  end if;
  update public.social_publishing_outbox o
     set status=v_target,
         provider_key=v_provider,
         external_post_id=coalesce(nullif(p_payload->>'external_post_id',''),o.external_post_id),
         external_permalink=coalesce(nullif(p_payload->>'external_permalink',''),o.external_permalink),
         published_at=case when v_target='published' then coalesce(nullif(p_payload->>'published_at','')::timestamptz,now()) else o.published_at end,
         last_error=case when v_target='failed' then coalesce(nullif(p_payload->>'error',''),'provider_reconciliation_failed') else null end,
         metadata=o.metadata || jsonb_build_object('last_reconciliation',p_payload),
         claimed_by=null,claimed_at=null,lease_expires_at=null
   where o.id=v_id
   returning o.* into v_row;
  if not found then raise exception 'job_not_found'; end if;
  return to_jsonb(v_row);
end;
$$;

create or replace function public.worker_v2_outbox_import_legacy(p_campaigns jsonb)
returns jsonb
language sql
security definer
set search_path = public
as $$
  -- Deliberately fail-closed after the database reset: old campaigns must not be
  -- silently re-imported and published without fresh verification.
  select jsonb_build_object('imported',0,'skipped',coalesce(jsonb_array_length(p_campaigns),0),'reason','legacy_import_disabled_on_vmdb');
$$;

alter table public.social_publishing_outbox enable row level security;
alter table public.social_distribution_metrics enable row level security;

revoke all on public.social_publishing_outbox from anon, authenticated;
revoke all on public.social_distribution_metrics from anon, authenticated;
grant all on public.social_publishing_outbox to service_role;
grant all on public.social_distribution_metrics to service_role;

do $$
declare f record;
begin
  for f in
    select p.oid::regprocedure as signature
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public' and p.proname in (
      'vmdb_social_outbox_refill','social_outbox_release_expired_leases','worker_v2_outbox_health',
      'worker_v2_outbox_peek','social_outbox_claim_provider','socialscheduler_claim_provider_capacity',
      'worker_v3_outbox_claim_capacity','worker_v2_outbox_claim','worker_v3_outbox_refill','worker_v3_outbox_ack',
      'worker_v3_delivery_metrics_batch','worker_v3_optimize_week','worker_v2_outbox_reconcile',
      'socialscheduler_provider_reconcile_candidates','worker_v11_delivery_reconcile','worker_v2_outbox_import_legacy'
    )
  loop
    execute format('revoke all on function %s from public, anon, authenticated',f.signature);
    execute format('grant execute on function %s to service_role',f.signature);
  end loop;
end $$;

comment on table public.social_publishing_outbox is 'Canonical VMDB SocialMarket -> SocialScheduler execution queue.';
comment on function public.vmdb_social_outbox_refill(integer) is 'Fail-closed refill from approved VMDB social presentation intelligence.';
