'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
export default function Merchants(){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data}=await supabase.from('merchant_profiles').select('merchant_name,internal_trust_score,trust_score,trust_confidence,external_reputation_score,external_reputation_confidence,external_risk_flag,external_risk_reason,complaint_risk_score,review_footprint_score,business_identity_score,official_domain,domain_age_years,evidence_count,active_offer_count,duplicate_win_rate,last_researched_at').order('trust_score',{ascending:false}).limit(300);setRows(data||[]);setLoading(false)})()},[]);
 const pct=v=>v==null?'—':`${Math.round(Number(v)*100)}%`;
 return <main><div className="hero"><div><div className="eyebrow">Evidence-first merchant selection</div><h1>Merchant Trust</h1><p className="sub">Internal feed reliability + external web reputation + complaint-risk corroboration. Ο φθηνότερος merchant δεν κερδίζει αυτόματα· externally risky merchant δεν μπορεί να γίνει preferred offer.</p></div></div><div className="card">{loading?<p className="muted">Loading merchant evidence…</p>:rows.length===0?<p className="muted">Δεν υπάρχουν ακόμη merchant profiles. Θα δημιουργηθούν μετά το πραγματικό feed import.</p>:<table className="table"><thead><tr><th>Merchant</th><th>Final Trust</th><th>Internal</th><th>External</th><th>Ext. confidence</th><th>Complaint risk</th><th>Identity</th><th>Domain age</th><th>Evidence</th><th>Risk</th></tr></thead><tbody>{rows.map(m=><tr key={m.merchant_name}><td><strong>{m.merchant_name}</strong><div className="muted">{m.official_domain||'domain pending'}</div></td><td className={Number(m.trust_score)>=80?'score good':Number(m.trust_score)>=65?'score warn':'score bad'}>{Number(m.trust_score||0).toFixed(1)}</td><td>{m.internal_trust_score==null?'—':Number(m.internal_trust_score).toFixed(0)}</td><td>{m.external_reputation_score==null?'—':Number(m.external_reputation_score).toFixed(0)}</td><td>{pct(m.external_reputation_confidence)}</td><td className={Number(m.complaint_risk_score||0)>=80?'bad':''}>{Number(m.complaint_risk_score||0).toFixed(0)}</td><td>{Number(m.business_identity_score||0).toFixed(0)}</td><td>{m.domain_age_years==null?'—':`${Number(m.domain_age_years).toFixed(1)}y`}</td><td>{m.evidence_count||0}</td><td>{m.external_risk_flag?<span className="pill bad">BLOCK</span>:<span className="pill">OK</span>}</td></tr>)}</tbody></table>}<p className="muted" style={{marginTop:14}}>External reputation είναι confidence-weighted. Με λίγα ή αδύναμα sources συρρικνώνεται προς neutral αντί να υπερεκτιμάται.</p></div></main>
}
