'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
export default function Merchants(){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data}=await supabase.from('merchant_profiles').select('merchant_name,trust_score,trust_confidence,active_offer_count,valid_tracking_ratio,image_quality_ratio,stock_reliability_ratio,validity_reliability_ratio,price_outlier_ratio,duplicate_win_rate,external_reputation_score,evidence,calculated_at').order('trust_score',{ascending:false}).limit(300);setRows(data||[]);setLoading(false)})()},[]);
 const pct=v=>v==null?'—':`${Math.round(Number(v)*100)}%`;
 return <main><div className="hero"><div><div className="eyebrow">Offer Resolution</div><h1>Merchant Trust</h1><p className="sub">Όταν το ίδιο προϊόν υπάρχει σε πολλούς merchants, επιλέγεται μία canonical offer. Το trust έχει μεγαλύτερο βάρος από τη χαμηλότερη τιμή.</p></div></div><div className="card">{loading?<p className="muted">Loading merchant evidence…</p>:rows.length===0?<p className="muted">Δεν υπάρχουν ακόμη merchant profiles. Θα δημιουργηθούν αμέσως μετά το feed import.</p>:<table className="table"><thead><tr><th>Merchant</th><th>Trust</th><th>Confidence</th><th>Offers</th><th>Tracking</th><th>Images</th><th>Stock</th><th>Validity</th><th>Price outliers</th><th>Duplicate wins</th></tr></thead><tbody>{rows.map(m=><tr key={m.merchant_name}><td><strong>{m.merchant_name}</strong></td><td className={Number(m.trust_score)>=80?'score good':Number(m.trust_score)>=65?'score warn':'score bad'}>{Number(m.trust_score||0).toFixed(1)}</td><td>{pct(m.trust_confidence)}</td><td>{m.active_offer_count}</td><td>{pct(m.valid_tracking_ratio)}</td><td>{pct(m.image_quality_ratio)}</td><td>{pct(m.stock_reliability_ratio)}</td><td>{pct(m.validity_reliability_ratio)}</td><td>{pct(m.price_outlier_ratio)}</td><td>{pct(m.duplicate_win_rate)}</td></tr>)}</tbody></table>}</div></main>
}
