'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
import styles from './configuration.module.css';

const presets={
 Balanced:{profile_name:'Balanced',min_expected_commission_eur:10,min_merchant_trust:30,min_validated_pain_clusters:1,min_audit_overall:70,min_pain_fit:60,min_product_evidence:60,min_pain_evidence_count:1,min_pain_source_diversity:1,min_pain_severity:0,min_commercial_intent:0,min_greek_demand:0,max_competition:100,pain_rag_limit:8,theme_rag_limit:5,ai_batch:1,ai_max_candidates:4,ai_offers_per_product:1,max_ai_batch_failure_rate:.25,ai_thinking_mode:'auto'},
 Conservative:{profile_name:'Conservative',min_expected_commission_eur:15,min_merchant_trust:60,min_validated_pain_clusters:2,min_audit_overall:82,min_pain_fit:72,min_product_evidence:72,min_pain_evidence_count:3,min_pain_source_diversity:2,min_pain_severity:55,min_commercial_intent:50,min_greek_demand:45,max_competition:65,pain_rag_limit:6,theme_rag_limit:4,ai_batch:1,ai_max_candidates:12,ai_offers_per_product:1,max_ai_batch_failure_rate:.15,ai_thinking_mode:'auto'},
 Exploration:{profile_name:'Exploration',min_expected_commission_eur:10,min_merchant_trust:20,min_validated_pain_clusters:1,min_audit_overall:65,min_pain_fit:50,min_product_evidence:50,min_pain_evidence_count:1,min_pain_source_diversity:1,min_pain_severity:25,min_commercial_intent:20,min_greek_demand:20,max_competition:85,pain_rag_limit:12,theme_rag_limit:7,ai_batch:2,ai_max_candidates:40,ai_offers_per_product:2,max_ai_batch_failure_rate:.30,ai_thinking_mode:'auto'}
};
const labels={
 min_expected_commission_eur:['Minimum expected commission','€','Hard commercial gate; cannot go below €10.'],min_merchant_trust:['Minimum merchant trust','/100','Merchant quality threshold before AI.'],min_validated_pain_clusters:['Minimum validated pains available','','Pipeline refuses AI phase if fewer exist.'],min_audit_overall:['Minimum Skeptic overall','/100','AI audit threshold after verdict VALIDATED.'],min_pain_fit:['Minimum pain-solution fit','/100','How strongly product must solve accepted pain.'],min_product_evidence:['Minimum product evidence','/100','Combined evidence confidence threshold.'],min_pain_evidence_count:['Minimum evidence per pain','','Raw evidence count behind a pain cluster.'],min_pain_source_diversity:['Minimum source diversity','','Independent source types behind a pain.'],min_pain_severity:['Minimum pain severity','/100','Ignore weak inconveniences below this level.'],min_commercial_intent:['Minimum commercial intent','/100','Prefer pains with buying/solution intent.'],min_greek_demand:['Minimum Greek demand','/100','Pain demand gate before the AI sees it.'],max_competition:['Maximum competition','/100','Reject pains above this competition score.'],pain_rag_limit:['Pain RAG candidates','','Max pains supplied to Product Research.'],theme_rag_limit:['Theme RAG candidates','','Max seasonal themes supplied to AI.'],ai_batch:['AI batch size','','Products per DeepSeek request.'],ai_max_candidates:['AI candidates per run','','Cost/coverage control.'],ai_offers_per_product:['Offers per canonical product','','How many merchant offers AI may compare.'],max_ai_batch_failure_rate:['AI failure circuit breaker','','Stop run if failure ratio exceeds this.']
};
const scoreLabels={pain_gap_fit:'Pain-gap fit',merchant_opportunity:'Merchant whitespace',greek_demand:'Greek demand',commission:'Expected commission',inverse_competition:'Inverse competition',seasonal:'Seasonal relevance',merchant_trust:'Merchant trust',discount:'Discount',evidence_confidence:'Evidence confidence'};

function Field({name,value,onChange}){const [label,suffix,help]=labels[name];return <label className={styles.field}><span><b>{label}</b><small>{help}</small></span><div><input type="number" step={name==='max_ai_batch_failure_rate'?0.01:1} value={value??''} onChange={e=>onChange(name,e.target.value===''?'':Number(e.target.value))}/><em>{suffix}</em></div></label>}

export default function Configuration(){
 const [cfg,setCfg]=useState(null),[meta,setMeta]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState('');
 async function load(){setLoading(true);const {data,error}=await supabase.rpc('admin_get_product_config');if(error)setError(error.message);else{setCfg(data.config);setMeta(data);setError('')}setLoading(false)}
 useEffect(()=>{load()},[]);
 const scoreSum=useMemo(()=>Object.values(cfg?.score_weights||{}).reduce((s,x)=>s+Number(x||0),0),[cfg]);
 const preSum=useMemo(()=>Object.values(cfg?.preliminary_weights||{}).reduce((s,x)=>s+Number(x||0),0),[cfg]);
 const update=(k,v)=>setCfg(c=>({...c,[k]:v}));
 const weight=(group,k,v)=>setCfg(c=>({...c,[group]:{...c[group],[k]:Number(v)}}));
 function preset(name){setCfg(c=>({...c,...presets[name]}));setMsg(`${name} preset loaded locally — Save to activate.`)}
 async function save(){setSaving(true);setMsg('');setError('');const {data,error}=await supabase.rpc('admin_update_product_config',{p_config:cfg});if(error)setError(error.message);else{setCfg(data.config);setMeta(data);setMsg(`Saved configuration v${data.version}. It becomes effective on the next Product Intelligence run.`)}setSaving(false)}
 async function reset(){setSaving(true);const {data,error}=await supabase.rpc('admin_reset_product_config');if(error)setError(error.message);else{setCfg(data.config);setMeta(data);setMsg(`Reset to safe defaults · v${data.version}.`)}setSaving(false)}
 if(loading)return <main className={styles.wrap}><div className={styles.loading}>Loading runtime policy…</div></main>;
 if(!cfg)return <main className={styles.wrap}><div className={styles.error}>{error||'Configuration unavailable'}</div></main>;
 return <main className={styles.wrap}>
  <header className={styles.hero}><div><span className={styles.eyebrow}>Runtime policy control</span><h1>Product Intelligence Configuration</h1><p>Change hard filters, AI acceptance criteria, RAG depth, run limits and scoring weights without editing code.</p></div><div className={styles.actions}><button onClick={reset} disabled={saving}>Reset defaults</button><button className={styles.primary} onClick={save} disabled={saving||scoreSum!==100||preSum!==100}>{saving?'Saving…':'Save & activate'}</button></div></header>
  {error&&<div className={styles.error}>{error}</div>}{msg&&<div className={styles.success}>{msg}</div>}
  <div className={styles.meta}><span>Version <b>{meta?.version??'—'}</b></span><span>Profile <b>{cfg.profile_name||'Custom'}</b></span><span>Updated <b>{meta?.updated_at?new Date(meta.updated_at).toLocaleString('el-GR'):'—'}</b></span><span>By <b>{meta?.updated_by||'—'}</b></span></div>
  <section className={styles.presets}><button onClick={()=>preset('Balanced')}>Balanced</button><button onClick={()=>preset('Conservative')}>Conservative</button><button onClick={()=>preset('Exploration')}>Exploration</button><span>Presets only populate the form. Nothing changes until Save.</span></section>

  <section className={styles.grid2}>
   <div className={styles.panel}><span className={styles.eyebrow}>Stage 1</span><h2>Deterministic hard filters</h2><Field name="min_expected_commission_eur" value={cfg.min_expected_commission_eur} onChange={update}/><Field name="min_merchant_trust" value={cfg.min_merchant_trust} onChange={update}/><Field name="min_greek_demand" value={cfg.min_greek_demand} onChange={update}/><Field name="max_competition" value={cfg.max_competition} onChange={update}/></div>
   <div className={styles.panel}><span className={styles.eyebrow}>Stage 2</span><h2>Pain evidence gates</h2><Field name="min_validated_pain_clusters" value={cfg.min_validated_pain_clusters} onChange={update}/><Field name="min_pain_evidence_count" value={cfg.min_pain_evidence_count} onChange={update}/><Field name="min_pain_source_diversity" value={cfg.min_pain_source_diversity} onChange={update}/><Field name="min_pain_severity" value={cfg.min_pain_severity} onChange={update}/><Field name="min_commercial_intent" value={cfg.min_commercial_intent} onChange={update}/></div>
  </section>

  <section className={styles.grid2}>
   <div className={styles.panel}><span className={styles.eyebrow}>Stage 3</span><h2>AI acceptance criteria</h2><Field name="min_audit_overall" value={cfg.min_audit_overall} onChange={update}/><Field name="min_pain_fit" value={cfg.min_pain_fit} onChange={update}/><Field name="min_product_evidence" value={cfg.min_product_evidence} onChange={update}/><label className={styles.field}><span><b>AI thinking mode</b><small>Auto enables deeper reasoning only for complex cases.</small></span><select value={cfg.ai_thinking_mode||'auto'} onChange={e=>update('ai_thinking_mode',e.target.value)}><option value="auto">Auto</option><option value="on">Always on</option><option value="off">Always off</option></select></label></div>
   <div className={styles.panel}><span className={styles.eyebrow}>Operations</span><h2>Cost & coverage controls</h2><Field name="pain_rag_limit" value={cfg.pain_rag_limit} onChange={update}/><Field name="theme_rag_limit" value={cfg.theme_rag_limit} onChange={update}/><Field name="ai_batch" value={cfg.ai_batch} onChange={update}/><Field name="ai_max_candidates" value={cfg.ai_max_candidates} onChange={update}/><Field name="ai_offers_per_product" value={cfg.ai_offers_per_product} onChange={update}/><Field name="max_ai_batch_failure_rate" value={cfg.max_ai_batch_failure_rate} onChange={update}/></div>
  </section>

  <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>Final ranking</span><h2>Opportunity score weights</h2></div><div className={scoreSum===100?styles.sumOk:styles.sumBad}>Total {scoreSum}%</div></div><div className={styles.weights}>{Object.entries(scoreLabels).map(([k,label])=><label key={k}><span>{label}</span><input type="number" min="0" max="100" value={cfg.score_weights?.[k]??0} onChange={e=>weight('score_weights',k,e.target.value)}/><em>%</em></label>)}</div><p className={styles.note}>Weights must total exactly 100%. Hard gates always run before this score.</p></section>

  <section className={styles.grid2}>
   <div className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>Pre-AI ranking</span><h2>Candidate ordering weights</h2></div><div className={preSum===100?styles.sumOk:styles.sumBad}>Total {preSum}%</div></div><div className={styles.weights}>{[['commission','Commission'],['merchant_whitespace','Merchant whitespace'],['demand','Demand']].map(([k,label])=><label key={k}><span>{label}</span><input type="number" value={cfg.preliminary_weights?.[k]??0} onChange={e=>weight('preliminary_weights',k,e.target.value)}/><em>%</em></label>)}</div></div>
   <div className={`${styles.panel} ${styles.safety}`}><span className={styles.eyebrow}>Non-configurable safety</span><h2>Rules you cannot switch off</h2><ul><li>Merchant must resolve deterministically.</li><li>Dominant / blocked merchants cannot be promoted.</li><li>Valid EUR price, tracking URL and image are mandatory.</li><li>Expected commission can never be configured below €10.</li><li>At least one validated pain match is required.</li><li>Skeptic verdict must be <b>VALIDATED</b>.</li><li>No fake AI fallback if DeepSeek fails.</li></ul></div>
  </section>
  <footer className={styles.footer}>Configuration is versioned and every change is written to the admin audit log.</footer>
 </main>
}
